<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

### 1. Tạo array 1 chiều


In [ ]:
# Tạo mảng 1 chiều
import numpy as np

# Cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
# Chuyển list sang numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39, 5])
print('Numpy array tạo bằng cách 2: ', a)

# Kích thước mảng, kiểu dữ liệu
print('Kích thước mảng: ', a.shape)
print('Kiểu dữ liệu mảng: ', a.dtype)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
Numpy array tạo bằng cách 2:  [ 1  9 15 39  5]
Kích thước mảng:  (5,)
Kiểu dữ liệu mảng:  int64


### 2. Array 2 chiều

In [ ]:
import numpy as np

# Mảng 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


### 3. Array 3 chiều

In [ ]:
import numpy as np

# Mảng 3 chiều
d = np.array([
    [[1., 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


### 4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [ ]:
import numpy as np

# Tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros(3)
f = np.ones((2, 3, 4)) * 9
g = np.full((1, 2, 3, 4), 8)
print('Zeros matrix:\n', e)
print('Nines matrix:\n', f)
print('Eights matrix:\n', g)

Zeros matrix:
 [0. 0. 0.]
Nines matrix:
 [[[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]

 [[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]]
Eights matrix:
 [[[[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]

  [[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]]]


### 5. Reshape và Flatten ma trận

#### 5.1. Reshape thay đổi kích thước ma trận

##### Để biết một ma trận có thể reshape sang những kích thước nào, bạn chỉ cần nhớ một quy tắc "vàng" duy nhất: Tổng số phần tử không được thay đổi.
##### Tính tổng số phần tử (N) bằng cách nhân tất cả các con số trong shape lại với nhau.
##### Ví dụ: $$N = 2 \times 2 \times 3 = 12 \text{ phần tử}$$

In [ ]:
import numpy as np

# Reshape thay đổi kích thước ma trận
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận e: ', e.shape)
f = e.reshape(3, 2)
print(f)
print('Kích thước ma trận f: ', f.shape)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(g)
print('Kích thước ma trận g: ', g.shape)
print('Reshape (3, 4)')
h = g.reshape(3, 4)
print(h)
print('Kích thước ma trận h: ', h.shape)
print('Reshape (3, 2, 2)')
i = g.reshape(3, 2, -1) # Để -1 cho numpy tự tính
print(i)
print('Kích thước ma trận g: ', i.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận e:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Kích thước ma trận f:  (3, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kích thước ma trận g:  (2, 2, 3)
Reshape (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kích thước ma trận h:  (3, 4)
Reshape (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Kích thước ma trận g:  (3, 2, 2)


#### 5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [ ]:
import numpy as np

# Plattern chuyển array nhiều chiều về 1 chiều
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận: ', e.shape)
f = e.flatten()
print(f)
print('Kích thước ma trận: ', f.shape)
g =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(g)
print('Kích thước ma trận: ', g.shape)
h = g.flatten()
print(f)
print('Kích thước ma trận: ', h.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)
[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)


### 6. Thêm dòng dữ liệu với hstack và vstack

In [ ]:
# Thêm dòng dữ liệu với hstack và vstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
print('Horizontal append\n', h_stack)
v_stack = np.vstack((a, b))
print('Vertical append\n', v_stack)

Horizontal append
 [1 2 3 4 5 6]
Vertical append
 [[1 2 3]
 [4 5 6]]


### 7. Sinh mảng số ngẫu nhiên

#### 7.1. Sinh mảng số nguyên ngẫu nhiên

In [ ]:
# Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(size = (5,), low = 0, high = 10)
print('Sinh số ngẫu nhiên ma trận 1 chiều:\n', a)
b = np.random.randint(10, size = (5,))
print('Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):\n', b)
c = np.random.randint(size = (3, 6), low = 5, high = 30)
print('Sinh số ngẫu nhiên ma trận 3x6:\n', c)

Sinh số ngẫu nhiên ma trận 1 chiều:
 [6 2 8 6 9]
Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):
 [9 3 9 9 6]
Sinh số ngẫu nhiên ma trận 3x6:
 [[10 15 24 19 28 28]
 [27 29 25 17  6 16]
 [21 12  6 28 27 23]]


#### 7.2. Sinh mảng số thực trong khoảng [0, 1]

In [ ]:
# Sinh mảng số thực ngẫu nhiên [0, 1)
a = np.random.rand(5)
print('Mảng 1 chiều:\n', a)
b = np.random.rand(3, 3, 2, 1)
print('Mảng 4 chiều:\n', b)

Mảng 1 chiều:
 [0.42933434 0.14730917 0.12983812 0.09215332 0.06633557]
Mảng 4 chiều:
 [[[[0.11840952]
   [0.63041849]]

  [[0.20604164]
   [0.25309509]]

  [[0.24217287]
   [0.84395147]]]


 [[[0.0291318 ]
   [0.42140669]]

  [[0.59875733]
   [0.06515978]]

  [[0.25195909]
   [0.55151776]]]


 [[[0.12075037]
   [0.82429669]]

  [[0.57787933]
   [0.37086086]]

  [[0.52174712]
   [0.4753236 ]]]]


#### 7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

##### Ta dùng hàm
##### Numpy.random.normal(loc, scale, size)
##### Trong đó
##### Loc: giá trị trung tâm
##### Scale: độ lệch chuẩn
##### Size: số phần tử trả về

##### Quy tắc dự đoán (3-Sigma):
##### 68% số sinh ra nằm trong: $[loc \pm scale]$
##### 95% số sinh ra nằm trong: $[loc \pm 2 \times scale]$ (Khoảng quan sát phổ biến nhất).
##### 99.7% số sinh ra nằm trong: $[loc \pm 3 \times scale]$ (Gần như toàn bộ).

##### Nếu bạn muốn sinh số ngẫu nhiên mà đa số nằm trong khoảng từ $A$ đến $B$:
##### 1. Chọn loc: Là điểm chính giữa của $A$ và $B$. ($loc = (A+B)/2$)
##### 2. Chọn scale: Lấy khoảng cách từ loc đến biên ($A$ hoặc $B$) rồi chia cho 2 hoặc 3.
#####  - Chia 2: Nếu muốn 95% số nằm trong khoảng.
#####  - Chia 3: Nếu muốn chắc chắn gần như 100% số nằm trong khoảng.
##### Ví dụ: Bạn muốn sinh số loanh quanh từ 10 đến 20:
#####  - loc = 15
#####  - scale = (20 - 15) / 2 = 2.5
#####  - Lệnh: np.random.normal(15, 2.5, size=...)

In [ ]:
# Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
a = np.random.normal(loc = 9, scale = 3, size = (4,))
print(a)

[10.57430149  8.44952632  8.33408085  9.14155096]


#### 7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [ ]:
# Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 5, 6, 10, 9], size = (9,))
print(a)

# Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9], size = (3, 5))
print(b)

[ 5  2  6  6  6  9  5 10  2]
[[2 9 1 4 4]
 [6 9 6 3 3]
 [2 4 2 5 9]]


### 8. Thay đổi giá trị của ma trận

In [ ]:
# Thay đổi giá trị của ma trận
A = np.matrix(np.ones((5, 6)))
print('The matrix\n', A)
np.array(A)[2] = 2 # array chỉ tạo bản sao của ma trận và tác động đến bản sao đó
print('The matrix with the change of row 3\n', A)
np.asarray(A)[2] = 2 # asarray tác động trực tiếp đến ma trận
print('The maxtrix with the change of row 3\n', A)

The matrix
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The matrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The maxtrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### 9. Sinh dãy số theo khoảng cho trước

#### 9.1. Dùng hàm arrange

In [ ]:
# Tạo 20 số nguyên từ 1 --> (n - 1)
a = np.arange(1, 20)
print(a)
# Tạo 20 số nguyên từ 1 --> (n - 1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#### 9.2. Dùng hàm linspace

In [ ]:
# Xếp num số cách đều nhau từ start đến end (tính luôn start và end) (num mặc định là 50)
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### 10. Index và slice

##### Quy tắc lấy Index trong ma trận
##### - Giá trị trước dấu ‘,’ là số dòng
##### - Giá trị sau dấu ‘,’ là số cột
##### - Muốn chọn một dòng hoặc cột cụ thể thì cần thêm dấu ‘:’

In [ ]:
# slice
a = np.array([(0, 1, 2), (3, 4, 5)])
print(a)
print('First row: ', a[0])
print('Second row: ', a[1])

# index
print('Second column: ', a[:, 1])
print('First row: ', a[0, :])
print('Fisrt row and 1 values: ', a[0, :4])

[[0 1 2]
 [3 4 5]]
First row:  [0 1 2]
Second row:  [3 4 5]
Second column:  [1 4]
First row:  [0 1 2]
Fisrt row and 1 values:  [0 1 2]


# Thực hành pandas

### Series là cấu trúc dữ liệu 1 chiều

In [ ]:
import pandas as pd

# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value: ', a[0])
b = pd.Series([1., 2., '3.'], index = ['a', 'b', 9])
print(b)
print('Second value: ', b['b'])
print('Third value: ', b[9])

# Tạo pandas series từ dictionary
calories = {"day 1": 420, "day 2": 380, 3: 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
9     3.
dtype: object
Second value:  2.0
Third value:  3.
day 1    420
day 2    380
3        390
dtype: int64


### Chuyển đổi mạng dạng Numpy sang Pandas và ngược lại

In [ ]:
# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy:
 [[1 2]
 [3 4]]


### Tạo DataFrame 2 chiều có tên cột

In [ ]:
dict = {'Tên': ['Văn', 'Thư'], 'Tuổi': [21, 21]}
df = pd.DataFrame(dict)
print(df)

   Tên  Tuổi
0  Văn    21
1  Thư    21


### In 5 dòng đầu tiên

In [ ]:
a = np.random.randint(0, 9, size= (20, 4))
df = pd.DataFrame(a, columns = ['Cột 1', 'Cột 2', 'Cột 3', "Cột 4"])
print('In tất cả:\n', df)
print('In 5 dòng đầu tiên:\n', df.head())
print('In 15 dòng (trừ 5 dòng cuối):\n', df.head(-5))

In tất cả:
     Cột 1  Cột 2  Cột 3  Cột 4
0       4      7      5      5
1       3      8      7      0
2       2      1      6      4
3       1      8      0      4
4       5      5      0      7
5       5      4      8      7
6       5      8      6      7
7       8      4      6      7
8       5      6      7      0
9       8      0      6      3
10      5      3      2      2
11      3      3      6      8
12      1      2      4      1
13      7      0      0      0
14      1      3      3      2
15      6      2      6      7
16      7      6      3      8
17      3      1      6      7
18      4      3      3      4
19      2      3      5      0
In 5 dòng đầu tiên:
    Cột 1  Cột 2  Cột 3  Cột 4
0      4      7      5      5
1      3      8      7      0
2      2      1      6      4
3      1      8      0      4
4      5      5      0      7
In 15 dòng (trừ 5 dòng cuối):
     Cột 1  Cột 2  Cột 3  Cột 4
0       4      7      5      5
1       3      8      7      0
2       2   

### Chọn dòng, cột

In [ ]:
a = np.random.rand(20, 5)
df = pd.DataFrame(a, columns = ['Số 1', 'Số 2', 'Số 3', 'Số 4', 'Số 5'])
print('Chọn 5 dòng cột 4:\n', df['Số 4'].head())
print('Chọn 3 dòng tất cả cột:\n', df[0:3])
print('Chọn 3 cột 5 dòng đầu tiên:\n', df.loc[0:4, 'Số 1':'Số 3'])
print("Chọn cột 2 và 3:\n", df[["Số 2", "Số 3"]].head())
print('Chọn nhiều dòng nhiều cột dùng loc:\n', df.loc[[0, 2, 4], ['Số 1', 'Số 3', 'Số 5']]) # loc lấy theo tên (nhãn)
print('Chọn nhiều dòng nhiều cột dùng iloc:\n', df.iloc[[0, 2, 4], [0, 2, 4]]) # iloc lấy theo vị trí (index)
print('Chọn 3 dòng, 2 cột đầu tiên:\n', df.iloc[:3, :2])

# Xóa cột
df.drop(columns = ['Số 3', 'Số 4'], inplace = True)  # inplace = True, áp dụng trực tiếp cho bảng
print(df)

# Xóa dòng
df.drop(index=[0, 1], inplace=True)
print(df)

Chọn 5 dòng cột 4:
 0    0.414317
1    0.136141
2    0.992300
3    0.247727
4    0.247500
Name: Số 4, dtype: float64
Chọn 3 dòng tất cả cột:
        Số 1      Số 2      Số 3      Số 4      Số 5
0  0.256542  0.782318  0.386935  0.414317  0.286787
1  0.133760  0.655452  0.606346  0.136141  0.380757
2  0.252616  0.729980  0.560686  0.992300  0.873352
Chọn 3 cột 5 dòng đầu tiên:
        Số 1      Số 2      Số 3
0  0.256542  0.782318  0.386935
1  0.133760  0.655452  0.606346
2  0.252616  0.729980  0.560686
3  0.569427  0.575929  0.849163
4  0.902598  0.358979  0.669798
Chọn cột 2 và 3:
        Số 2      Số 3
0  0.782318  0.386935
1  0.655452  0.606346
2  0.729980  0.560686
3  0.575929  0.849163
4  0.358979  0.669798
Chọn nhiều dòng nhiều cột dùng loc:
        Số 1      Số 3      Số 5
0  0.256542  0.386935  0.286787
2  0.252616  0.560686  0.873352
4  0.902598  0.669798  0.752423
Chọn nhiều dòng nhiều cột dùng iloc:
        Số 1      Số 3      Số 5
0  0.256542  0.386935  0.286787
2  0.252616 

### Nối nhiều dataframe

In [ ]:
df1 = pd.DataFrame({'Name':['Gojo Satoru', 'Yuta Okutsu', 'Ryomen Sukuna'],
                    'Skills':['Limitless', 'Copy', 'Shrine']})
df2 = pd.DataFrame({'Name':['Yuki Tsukumo', 'Gojo Satoru'],
                    'Skills':['Star Rage', 'Limitless']}, index=[8, 9])
df_concat = pd.concat([df1, df2], ignore_index=True)
print('DataFrame concat:\n', df_concat, end='\n\n')

# Xóa những giá trị ở cột name trùng nhau
print('Drop duplicate in DataFrame concat:\n', df_concat.drop_duplicates('Name'),end='\n\n')

# Sắp xếp giá trị theo cột (tăng dần)
print('Sort values in Dataframe:\n', df_concat.sort_values(by='Name'),end='\n\n')

# Sắp xếp giá trị theo cột (giảm dần)
print('Sort values in Dataframe:\n', df_concat.sort_values(by=['Name', 'Skills'], ascending=[True, False]),end='\n\n')

# Đổi tên cột
print('Rename colums of DataFrame:\n', df_concat.rename(columns={'Name':'Tên', 'Skills':'Kỹ năng'}))

DataFrame concat:
             Name     Skills
0    Gojo Satoru  Limitless
1    Yuta Okutsu       Copy
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
4    Gojo Satoru  Limitless

Drop duplicate in DataFrame concat:
             Name     Skills
0    Gojo Satoru  Limitless
1    Yuta Okutsu       Copy
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage

Sort values in Dataframe:
             Name     Skills
0    Gojo Satoru  Limitless
4    Gojo Satoru  Limitless
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
1    Yuta Okutsu       Copy

Sort values in Dataframe:
             Name     Skills
0    Gojo Satoru  Limitless
4    Gojo Satoru  Limitless
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
1    Yuta Okutsu       Copy

Rename colums of DataFrame:
              Tên    Kỹ năng
0    Gojo Satoru  Limitless
1    Yuta Okutsu       Copy
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
4    Gojo Satoru  Limitless


### Đọc dữ liệu từ file csv

##### Trong đó:
##### - filepath_or_buffer: Path or URL with the data
##### - sep=', ': Define the delimiter to use
##### - ‘names=None’: Name the columns. If the dataset has ten columns, you need to pass ten names
##### - ‘index_col=None’: If yes, the first column is used as a row index
##### - ‘skipinitialspace=False’: Skip spaces after delimiter

In [ ]:
# Tạo file csv
import csv
data = [['Tên', 'Tuổi', 'Chuyên ngành'],
        ['Hoàng', 22, 'Công nghệ phần mềm'],
        ['Vỹ', 21, 'Khoa học máy tính']
]
with open('sinh_vien.csv', 'w', newline='', encoding='utf-8') as file:
  writer = csv.writer(file)
  writer.writerows(data)

# Đọc file csv
path = 'sinh_vien.csv'
# names=None --> lấy dòng đầu tiên làm tên cột, từ dòng thứ 2 làm giá trị
df = pd.read_csv(path, skipinitialspace=True, names=None, index_col=None, sep=",")
print(df)
print(df.shape,end='\n\n')

# Tên cột đa tầng
df_multiheader = pd.read_csv(path, header=[0, 1], index_col=None, skipinitialspace=True, sep=',')
print(df_multiheader)
print(df_multiheader.shape,end='\n\n')

# Tên cột đa tầng cách 2
df_multiheader = pd.read_csv(path, header=list(range(0, 2)), index_col=None, skipinitialspace=True, sep=',')
print(df_multiheader)
print(df_multiheader.shape,end='\n\n')

# Tự đặt tên cột
columns=['Name', 'Age', 'Major']
df_rename=pd.read_csv(filepath_or_buffer=path, skiprows=[2], names=columns, index_col=None, skipinitialspace=False)
print(df_rename)
print(df_rename.shape,end='\n\n')

     Tên  Tuổi        Chuyên ngành
0  Hoàng    22  Công nghệ phần mềm
1     Vỹ    21   Khoa học máy tính
(2, 3)

    Tên Tuổi       Chuyên ngành
  Hoàng   22 Công nghệ phần mềm
0    Vỹ   21  Khoa học máy tính
(1, 3)

    Tên Tuổi       Chuyên ngành
  Hoàng   22 Công nghệ phần mềm
0    Vỹ   21  Khoa học máy tính
(1, 3)

    Name   Age               Major
0    Tên  Tuổi        Chuyên ngành
1  Hoàng    22  Công nghệ phần mềm
(2, 3)



### Gom nhóm dữ liệu

##### 3 cách kết nối mới file ngoài máy tính
##### - Cách 1 (Kéo thả): Bấm vào icon Thư mục 📁 bên trái rồi kéo file từ máy tính thả trực tiếp vào giao diện Colab để dùng ngay lập tức.

##### - Cách 2 (Hộp thoại Upload): Chạy đoạn code from google.colab import files; files.upload() để hiện nút bấm chọn file trực quan từ máy thật.

##### - Cách 3 (Gắn Google Drive): Chạy code from google.colab import drive; drive.mount('/content/drive') để kết nối và đọc file lưu trữ vĩnh viễn trên Drive.

In [ ]:
# Chuẩn bị dữ liệu mẫu phân cấp rõ ràng để gom nhóm
data = [
    ['Tên', 'Học viện', 'Cấp bậc', 'Điểm kiểm tra'],
    ['Gojo Satoru', 'Tokyo', 'Đặc cấp', 100],
    ['Yuta Okutsu', 'Tokyo', 'Đặc cấp', 95],
    ['Geto Suguru', 'Tokyo', 'Đặc cấp', 92],
    ['Itadori Yuji', 'Tokyo', 'Cấp 1', 85],
    ['Fushiguro Megumi', 'Tokyo', 'Cấp 1', 80],
    ['Kugisaki Nobara', 'Tokyo', 'Cấp 2', 75],
    ['Inumaki Toge', 'Tokyo', 'Cấp 2', 78],
    ['Todo Aoi', 'Kyoto', 'Cấp 1', 90],
    ['Mai Zenin', 'Kyoto', 'Cấp 3', 65],
    ['Miwa Kasumi', 'Kyoto', 'Cấp 3', 60],
    ['Kamo Noritoshi', 'Kyoto', 'Cấp 1', 82],
    ['Zenin Naobito', 'Kyoto', 'Cấp 1', 88]
]

with open(file='jujutsu_kaisen.csv', mode='w', newline='', encoding='utf-8') as file:
  writer = csv.writer(file)
  writer.writerows(data)

path = 'jujutsu_kaisen.csv'
df = pd.read_csv(path, skipinitialspace=True, names=None, sep=',', index_col=None)
print('Toàn bộ file:\n', df)
print(df.dtypes)
print(df.shape)
print('\n')

# Gom nhóm tính toán 1 cột
print('Gom nhóm theo học viện và cấp bậc (trung bình điểm kiểm tra):\n', df.groupby(['Học viện', 'Cấp bậc'])['Điểm kiểm tra'].mean())
print(df.dtypes)
print(df.shape)
print('\n')

# Thêm cột mới và ghi vào file csv
df['Tuổi'] = [28, 17, 28, 15, 15, 15, 17, 18, 16, 17, 18, 71]
path_afteradd='jujutsu_kaisen.csv'
df.to_csv(path_afteradd, index=False, encoding='utf-8') # index=False --> Phải có để Pandas không tự chèn thêm một cột số thứ tự vô danh
df_afteradd = pd.read_csv(filepath_or_buffer='jujutsu_kaisen.csv', skipinitialspace=True, names=None, sep=',')
print('Dữ liệu sau bổ sung:\n', df_afteradd)
print(df.dtypes)
print(df.shape)
print('\n')

# Gom nhóm  tính toán 2 cột
df_result = df.groupby(['Cấp bậc']).agg({
    'Điểm kiểm tra': ['min', 'max', 'mean'],
    'Tuổi': ['min', 'max', 'mean']
})
print('Gom nhóm theo cấp bậc:\n', df_result)
print(df_result.dtypes)
print(df_result.shape)
print('\n')

Toàn bộ file:
                  Tên Học viện  Cấp bậc  Điểm kiểm tra
0        Gojo Satoru    Tokyo  Đặc cấp            100
1        Yuta Okutsu    Tokyo  Đặc cấp             95
2        Geto Suguru    Tokyo  Đặc cấp             92
3       Itadori Yuji    Tokyo    Cấp 1             85
4   Fushiguro Megumi    Tokyo    Cấp 1             80
5    Kugisaki Nobara    Tokyo    Cấp 2             75
6       Inumaki Toge    Tokyo    Cấp 2             78
7           Todo Aoi    Kyoto    Cấp 1             90
8          Mai Zenin    Kyoto    Cấp 3             65
9        Miwa Kasumi    Kyoto    Cấp 3             60
10    Kamo Noritoshi    Kyoto    Cấp 1             82
11     Zenin Naobito    Kyoto    Cấp 1             88
Tên              object
Học viện         object
Cấp bậc          object
Điểm kiểm tra     int64
dtype: object
(12, 4)


Gom nhóm theo học viện và cấp bậc (trung bình điểm kiểm tra):
 Học viện  Cấp bậc
Kyoto     Cấp 1      86.666667
          Cấp 3      62.500000
Tokyo     Cấp 1     

# Thực hành TensorFlow

In [1]:
import tensorflow as tf
import numpy as np

## 1. Tensor 0 chiều

### Tensor 0-chiều gọi là scalar chỉ chứa 1 giá trị và không có trục.

In [ ]:
# Kiểu mặc định là int32
rank_0_tensor = tf.constant(9)
print(rank_0_tensor)

r0_int8 = tf.constant(9, tf.int8)
print(r0_int8)

r0_float16 = tf.constant(9, tf.float16)
print(r0_float16)

r0_string = tf.constant('9', tf.string)
print(r0_string)

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int8)
tf.Tensor(9.0, shape=(), dtype=float16)
tf.Tensor(b'9', shape=(), dtype=string)


## 2. Tensor 1 chiều

### Tensor 1 chiều còn gọi là vector có 1 trục. Tensor 1-chiều giống như một danh sách

In [ ]:
rank_1_tensor = tf.constant([1, 2, 3, 4], dtype = tf.float16)
print(rank_1_tensor)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)


## 3. Tensor 2 chiều (ma trận)

### Là một ma trận hoặc có 2 trục

In [ ]:
rank_2_tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype = tf.int8)
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int8)


## 4. Tensor n chiều

In [ ]:
rank_3_tensor = tf.constant([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
    ], dtype=tf.int8)
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int8)


## 5. Thuộc tính của tensor

### Một tensor gồm có 3 thuộc tính:
### - Label (name)
### - Dimension (shape)
### - Data type (dtype)

In [ ]:
rank_3_tensor = tf.constant([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
    ], dtype=tf.int8)
print(rank_3_tensor)
print('shape', rank_3_tensor.shape)
print('type o f tensor', rank_3_tensor.dtype)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int8)
shape (2, 3, 4)
type 0f tensor <dtype: 'int8'>


## 6. Tạo tensor tự động gán giá trị ban đầu là 0

In [5]:
tensor_0 = tf.zeros(10)
print(tensor_0)
print(tensor_0.shape)
print(tensor_0.dtype, end="\n\n")

tensor_0_2d = tf.zeros([3, 5])
print(tensor_0_2d)
print(tensor_0_2d.shape)
print(tensor_0_2d.dtype, end="\n\n")

tensor_0_3d = tf.zeros([3, 5, 2])
print(tensor_0_3d)
print(tensor_0_3d.shape)
print(tensor_0_3d.dtype, end='\n\n')

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
(10,)
<dtype: 'float32'>

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)
(3, 5)
<dtype: 'float32'>

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(3, 5, 2), dtype=float32)
(3, 5, 2)
<dtype: 'float32'>



## 7. Tạo tensor tạo tự động gán giá trị ban đầu là 1

In [7]:
t_1 = tf.ones(10)
print(t_1)
print(t_1.shape)
print(t_1.dtype, end='\n\n')

t_1_2d = tf.ones([3, 5])
print(t_1_2d)
print(t_1_2d.shape)
print(t_1_2d.dtype, end='\n\n')

t_1_3d = tf.ones([3, 5, 2], tf.int8)
print(t_1_3d)
print(t_1_3d.shape)
print(t_1_3d.dtype, end='\n\n')

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
(10,)
<dtype: 'float32'>

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)
(3, 5)
<dtype: 'float32'>

tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]], shape=(3, 5, 2), dtype=int8)
(3, 5, 2)
<dtype: 'int8'>



## 8. Tạo tensor tự động với giá trị bất kì

In [8]:
t_9 = tf.fill([3, 5], 9, tf.int8)
print(t_9)
print(t_9.shape)
print(t_9.dtype,end='\n\n')

tf.Tensor(
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]], shape=(3, 5), dtype=int32)
(3, 5)
<dtype: 'int32'>



## 9. Tạo tensor 1 chiều với hàm linspace

In [9]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)
print(lin_tensor.shape)
print(lin_tensor.dtype)
# Code trên tạo 5 phần tử có giá trị trong khoảng [5.0, 20.0]

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)
(5,)
<dtype: 'float32'>
