<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

### 1. Tạo array 1 chiều


In [1]:
# Tạo mảng 1 chiều
import numpy as np

# Cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
# Chuyển list sang numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39, 5])
print('Numpy array tạo bằng cách 2: ', a)

# Kích thước mảng, kiểu dữ liệu
print('Kích thước mảng: ', a.shape)
print('Kiểu dữ liệu mảng: ', a.dtype)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
Numpy array tạo bằng cách 2:  [ 1  9 15 39  5]
Kích thước mảng:  (5,)
Kiểu dữ liệu mảng:  int64


### 2. Array 2 chiều

In [2]:
import numpy as np

# Mảng 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


### 3. Array 3 chiều

In [3]:
import numpy as np

# Mảng 3 chiều
d = np.array([
    [[1., 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


### 4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [4]:
import numpy as np

# Tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros(3)
f = np.ones((2, 3, 4)) * 9
g = np.full((1, 2, 3, 4), 8)
print('Zeros matrix:\n', e)
print('Nines matrix:\n', f)
print('Eights matrix:\n', g)

Zeros matrix:
 [0. 0. 0.]
Nines matrix:
 [[[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]

 [[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]]
Eights matrix:
 [[[[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]

  [[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]]]


### 5. Reshape và Flatten ma trận

#### 5.1. Reshape thay đổi kích thước ma trận

##### Để biết một ma trận có thể reshape sang những kích thước nào, bạn chỉ cần nhớ một quy tắc "vàng" duy nhất: Tổng số phần tử không được thay đổi.
##### Tính tổng số phần tử (N) bằng cách nhân tất cả các con số trong shape lại với nhau.
##### Ví dụ: $$N = 2 \times 2 \times 3 = 12 \text{ phần tử}$$

In [5]:
import numpy as np

# Reshape thay đổi kích thước ma trận
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận e: ', e.shape)
f = e.reshape(3, 2)
print(f)
print('Kích thước ma trận f: ', f.shape)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(g)
print('Kích thước ma trận g: ', g.shape)
print('Reshape (3, 4)')
h = g.reshape(3, 4)
print(h)
print('Kích thước ma trận h: ', h.shape)
print('Reshape (3, 2, 2)')
i = g.reshape(3, 2, -1) # Để -1 cho numpy tự tính
print(i)
print('Kích thước ma trận g: ', i.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận e:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Kích thước ma trận f:  (3, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kích thước ma trận g:  (2, 2, 3)
Reshape (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kích thước ma trận h:  (3, 4)
Reshape (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Kích thước ma trận g:  (3, 2, 2)


#### 5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [6]:
import numpy as np

# Plattern chuyển array nhiều chiều về 1 chiều
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận: ', e.shape)
f = e.flatten()
print(f)
print('Kích thước ma trận: ', f.shape)
g =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(g)
print('Kích thước ma trận: ', g.shape)
h = g.flatten()
print(f)
print('Kích thước ma trận: ', h.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)
[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)


### 6. Thêm dòng dữ liệu với hstack và vstack

In [7]:
# Thêm dòng dữ liệu với hstack và vstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
print('Horizontal append\n', h_stack)
v_stack = np.vstack((a, b))
print('Vertical append\n', v_stack)

Horizontal append
 [1 2 3 4 5 6]
Vertical append
 [[1 2 3]
 [4 5 6]]


### 7. Sinh mảng số ngẫu nhiên

#### 7.1. Sinh mảng số nguyên ngẫu nhiên

In [8]:
# Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(size = (5,), low = 0, high = 10)
print('Sinh số ngẫu nhiên ma trận 1 chiều:\n', a)
b = np.random.randint(10, size = (5,))
print('Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):\n', b)
c = np.random.randint(size = (3, 6), low = 5, high = 30)
print('Sinh số ngẫu nhiên ma trận 3x6:\n', c)

Sinh số ngẫu nhiên ma trận 1 chiều:
 [5 7 6 3 5]
Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):
 [5 7 3 5 9]
Sinh số ngẫu nhiên ma trận 3x6:
 [[18 19 24 12 11 29]
 [19 26 13 28 27 24]
 [26  5 14  5  7 18]]


#### 7.2. Sinh mảng số thực trong khoảng [0, 1]

In [9]:
# Sinh mảng số thực ngẫu nhiên [0, 1)
a = np.random.rand(5)
print('Mảng 1 chiều:\n', a)
b = np.random.rand(3, 3, 2, 1)
print('Mảng 4 chiều:\n', b)

Mảng 1 chiều:
 [0.12405473 0.65428874 0.792821   0.46397514 0.86991286]
Mảng 4 chiều:
 [[[[0.78760552]
   [0.1323536 ]]

  [[0.4124691 ]
   [0.09027322]]

  [[0.97960886]
   [0.60337645]]]


 [[[0.99182364]
   [0.45791536]]

  [[0.65286315]
   [0.7879466 ]]

  [[0.98938201]
   [0.16385273]]]


 [[[0.64653375]
   [0.4352384 ]]

  [[0.71890899]
   [0.21489035]]

  [[0.81226797]
   [0.6014849 ]]]]


#### 7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

##### Ta dùng hàm
##### Numpy.random.normal(loc, scale, size)
##### Trong đó
##### Loc: giá trị trung tâm
##### Scale: độ lệch chuẩn
##### Size: số phần tử trả về

##### Quy tắc dự đoán (3-Sigma):
##### 68% số sinh ra nằm trong: $[loc \pm scale]$
##### 95% số sinh ra nằm trong: $[loc \pm 2 \times scale]$ (Khoảng quan sát phổ biến nhất).
##### 99.7% số sinh ra nằm trong: $[loc \pm 3 \times scale]$ (Gần như toàn bộ).

##### Nếu bạn muốn sinh số ngẫu nhiên mà đa số nằm trong khoảng từ $A$ đến $B$:
##### 1. Chọn loc: Là điểm chính giữa của $A$ và $B$. ($loc = (A+B)/2$)
##### 2. Chọn scale: Lấy khoảng cách từ loc đến biên ($A$ hoặc $B$) rồi chia cho 2 hoặc 3.
#####  - Chia 2: Nếu muốn 95% số nằm trong khoảng.
#####  - Chia 3: Nếu muốn chắc chắn gần như 100% số nằm trong khoảng.
##### Ví dụ: Bạn muốn sinh số loanh quanh từ 10 đến 20:
#####  - loc = 15
#####  - scale = (20 - 15) / 2 = 2.5
#####  - Lệnh: np.random.normal(15, 2.5, size=...)

In [10]:
# Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
a = np.random.normal(loc = 9, scale = 3, size = (4,))
print(a)

[ 9.63644441 10.58462     8.44765951 11.16658014]


#### 7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [11]:
# Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 5, 6, 10, 9], size = (9,))
print(a)

# Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9], size = (3, 5))
print(b)

[2 2 9 5 6 9 6 9 2]
[[2 6 5 7 9]
 [9 9 4 7 1]
 [1 7 1 7 2]]


### 8. Thay đổi giá trị của ma trận

In [12]:
# Thay đổi giá trị của ma trận
A = np.matrix(np.ones((5, 6)))
print('The matrix\n', A)
np.array(A)[2] = 2 # array chỉ tạo bản sao của ma trận và tác động đến bản sao đó
print('The matrix with the change of row 3\n', A)
np.asarray(A)[2] = 2 # asarray tác động trực tiếp đến ma trận
print('The maxtrix with the change of row 3\n', A)

The matrix
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The matrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The maxtrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### 9. Sinh dãy số theo khoảng cho trước

#### 9.1. Dùng hàm arrange

In [13]:
# Tạo 20 số nguyên từ 1 --> (n - 1)
a = np.arange(1, 20)
print(a)
# Tạo 20 số nguyên từ 1 --> (n - 1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#### 9.2. Dùng hàm linspace

In [14]:
# Xếp num số cách đều nhau từ start đến end (tính luôn start và end) (num mặc định là 50)
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### 10. Index và slice

##### Quy tắc lấy Index trong ma trận
##### - Giá trị trước dấu ‘,’ là số dòng
##### - Giá trị sau dấu ‘,’ là số cột
##### - Muốn chọn một dòng hoặc cột cụ thể thì cần thêm dấu ‘:’

In [15]:
# slice
a = np.array([(0, 1, 2), (3, 4, 5)])
print(a)
print('First row: ', a[0])
print('Second row: ', a[1])

# index
print('Second column: ', a[:, 1])
print('First row: ', a[0, :])
print('Fisrt row and 1 values: ', a[0, :4])

[[0 1 2]
 [3 4 5]]
First row:  [0 1 2]
Second row:  [3 4 5]
Second column:  [1 4]
First row:  [0 1 2]
Fisrt row and 1 values:  [0 1 2]


# Thực hành pandas

### Series là cấu trúc dữ liệu 1 chiều

In [16]:
import pandas as pd

# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value: ', a[0])
b = pd.Series([1., 2., '3.'], index = ['a', 'b', 9])
print(b)
print('Second value: ', b['b'])
print('Third value: ', b[9])

# Tạo pandas series từ dictionary
calories = {"day 1": 420, "day 2": 380, 3: 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
9     3.
dtype: object
Second value:  2.0
Third value:  3.
day 1    420
day 2    380
3        390
dtype: int64


### Chuyển đổi mạng dạng Numpy sang Pandas và ngược lại

In [17]:
# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy:
 [[1 2]
 [3 4]]


### Tạo DataFrame 2 chiều có tên cột

In [18]:
dict = {'Tên': ['Văn', 'Thư'], 'Tuổi': [21, 21]}
df = pd.DataFrame(dict)
print(df)

   Tên  Tuổi
0  Văn    21
1  Thư    21


### In 5 dòng đầu tiên

In [19]:
a = np.random.randint(0, 9, size= (20, 4))
df = pd.DataFrame(a, columns = ['Cột 1', 'Cột 2', 'Cột 3', "Cột 4"])
print('In tất cả:\n', df)
print('In 5 dòng đầu tiên:\n', df.head())
print('In 15 dòng (trừ 5 dòng cuối):\n', df.head(-5))

In tất cả:
     Cột 1  Cột 2  Cột 3  Cột 4
0       2      4      5      1
1       4      7      2      1
2       1      8      8      4
3       7      3      6      2
4       6      7      6      2
5       0      4      2      7
6       6      7      8      5
7       6      7      8      5
8       3      1      7      6
9       2      5      5      5
10      4      0      6      8
11      2      6      4      2
12      5      0      4      4
13      3      0      6      4
14      0      3      0      7
15      6      6      0      0
16      5      2      3      5
17      7      7      2      6
18      1      8      2      7
19      4      5      5      2
In 5 dòng đầu tiên:
    Cột 1  Cột 2  Cột 3  Cột 4
0      2      4      5      1
1      4      7      2      1
2      1      8      8      4
3      7      3      6      2
4      6      7      6      2
In 15 dòng (trừ 5 dòng cuối):
     Cột 1  Cột 2  Cột 3  Cột 4
0       2      4      5      1
1       4      7      2      1
2       1   

### Chọn dòng, cột

In [20]:
a = np.random.rand(20, 5)
df = pd.DataFrame(a, columns = ['Số 1', 'Số 2', 'Số 3', 'Số 4', 'Số 5'])
print('Chọn 5 dòng cột 4:\n', df['Số 4'].head())
print('Chọn 3 dòng tất cả cột:\n', df[0:3])
print('Chọn 3 cột 5 dòng đầu tiên:\n', df.loc[0:4, 'Số 1':'Số 3'])
print("Chọn cột 2 và 3:\n", df[["Số 2", "Số 3"]].head())
print('Chọn nhiều dòng nhiều cột dùng loc:\n', df.loc[[0, 2, 4], ['Số 1', 'Số 3', 'Số 5']]) # loc lấy theo tên (nhãn)
print('Chọn nhiều dòng nhiều cột dùng iloc:\n', df.iloc[[0, 2, 4], [0, 2, 4]]) # iloc lấy theo vị trí (index)
print('Chọn 3 dòng, 2 cột đầu tiên:\n', df.iloc[:3, :2])

# Xóa cột
df.drop(columns = ['Số 3', 'Số 4'], inplace = True)  # inplace = True, áp dụng trực tiếp cho bảng
print(df)

# Xóa dòng
df.drop(index=[0, 1], inplace=True)
print(df)

Chọn 5 dòng cột 4:
 0    0.997509
1    0.994989
2    0.923129
3    0.811913
4    0.686754
Name: Số 4, dtype: float64
Chọn 3 dòng tất cả cột:
        Số 1      Số 2      Số 3      Số 4      Số 5
0  0.148402  0.196116  0.921749  0.997509  0.723546
1  0.350624  0.555152  0.063219  0.994989  0.678613
2  0.800964  0.654757  0.416963  0.923129  0.744555
Chọn 3 cột 5 dòng đầu tiên:
        Số 1      Số 2      Số 3
0  0.148402  0.196116  0.921749
1  0.350624  0.555152  0.063219
2  0.800964  0.654757  0.416963
3  0.023082  0.344379  0.025481
4  0.690698  0.673291  0.338391
Chọn cột 2 và 3:
        Số 2      Số 3
0  0.196116  0.921749
1  0.555152  0.063219
2  0.654757  0.416963
3  0.344379  0.025481
4  0.673291  0.338391
Chọn nhiều dòng nhiều cột dùng loc:
        Số 1      Số 3      Số 5
0  0.148402  0.921749  0.723546
2  0.800964  0.416963  0.744555
4  0.690698  0.338391  0.027683
Chọn nhiều dòng nhiều cột dùng iloc:
        Số 1      Số 3      Số 5
0  0.148402  0.921749  0.723546
2  0.800964 

### Nối nhiều dataframe

In [21]:
df1 = pd.DataFrame({'Name':['Gojo Satoru', 'Yuta Okutsu', 'Ryomen Sukuna'],
                    'Skills':['Limitless', 'Copy', 'Shrine']})
df2 = pd.DataFrame({'Name':['Yuki Tsukumo', 'Gojo Satoru'],
                    'Skills':['Star Rage', 'Limitless']}, index=[8, 9])
df_concat = pd.concat([df1, df2], ignore_index=True)
print('DataFrame concat:\n', df_concat, end='\n\n')

# Xóa những giá trị ở cột name trùng nhau
print('Drop duplicate in DataFrame concat:\n', df_concat.drop_duplicates('Name'),end='\n\n')

# Sắp xếp giá trị theo cột (tăng dần)
print('Sort values in Dataframe:\n', df_concat.sort_values(by='Name'),end='\n\n')

# Sắp xếp giá trị theo cột (giảm dần)
print('Sort values in Dataframe:\n', df_concat.sort_values(by=['Name', 'Skills'], ascending=[True, False]),end='\n\n')

# Đổi tên cột
print('Rename colums of DataFrame:\n', df_concat.rename(columns={'Name':'Tên', 'Skills':'Kỹ năng'}))

DataFrame concat:
             Name     Skills
0    Gojo Satoru  Limitless
1    Yuta Okutsu       Copy
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
4    Gojo Satoru  Limitless

Drop duplicate in DataFrame concat:
             Name     Skills
0    Gojo Satoru  Limitless
1    Yuta Okutsu       Copy
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage

Sort values in Dataframe:
             Name     Skills
0    Gojo Satoru  Limitless
4    Gojo Satoru  Limitless
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
1    Yuta Okutsu       Copy

Sort values in Dataframe:
             Name     Skills
0    Gojo Satoru  Limitless
4    Gojo Satoru  Limitless
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
1    Yuta Okutsu       Copy

Rename colums of DataFrame:
              Tên    Kỹ năng
0    Gojo Satoru  Limitless
1    Yuta Okutsu       Copy
2  Ryomen Sukuna     Shrine
3   Yuki Tsukumo  Star Rage
4    Gojo Satoru  Limitless


### Đọc dữ liệu từ file csv

##### Trong đó:
##### - filepath_or_buffer: Path or URL with the data
##### - sep=', ': Define the delimiter to use
##### - ‘names=None’: Name the columns. If the dataset has ten columns, you need to pass ten names
##### - ‘index_col=None’: If yes, the first column is used as a row index
##### - ‘skipinitialspace=False’: Skip spaces after delimiter

In [22]:
# Tạo file csv
import csv
data = [['Tên', 'Tuổi', 'Chuyên ngành'],
        ['Hoàng', 22, 'Công nghệ phần mềm'],
        ['Vỹ', 21, 'Khoa học máy tính']
]
with open('sinh_vien.csv', 'w', newline='', encoding='utf-8') as file:
  writer = csv.writer(file)
  writer.writerows(data)

# Đọc file csv
path = 'sinh_vien.csv'
# names=None --> lấy dòng đầu tiên làm tên cột, từ dòng thứ 2 làm giá trị
df = pd.read_csv(path, skipinitialspace=True, names=None, index_col=None, sep=",")
print(df)
print(df.shape,end='\n\n')

# Tên cột đa tầng
df_multiheader = pd.read_csv(path, header=[0, 1], index_col=None, skipinitialspace=True, sep=',')
print(df_multiheader)
print(df_multiheader.shape,end='\n\n')

# Tên cột đa tầng cách 2
df_multiheader = pd.read_csv(path, header=list(range(0, 2)), index_col=None, skipinitialspace=True, sep=',')
print(df_multiheader)
print(df_multiheader.shape,end='\n\n')

# Tự đặt tên cột
columns=['Name', 'Age', 'Major']
df_rename=pd.read_csv(filepath_or_buffer=path, skiprows=[2], names=columns, index_col=None, skipinitialspace=False)
print(df_rename)
print(df_rename.shape,end='\n\n')

     Tên  Tuổi        Chuyên ngành
0  Hoàng    22  Công nghệ phần mềm
1     Vỹ    21   Khoa học máy tính
(2, 3)

    Tên Tuổi       Chuyên ngành
  Hoàng   22 Công nghệ phần mềm
0    Vỹ   21  Khoa học máy tính
(1, 3)

    Tên Tuổi       Chuyên ngành
  Hoàng   22 Công nghệ phần mềm
0    Vỹ   21  Khoa học máy tính
(1, 3)

    Name   Age               Major
0    Tên  Tuổi        Chuyên ngành
1  Hoàng    22  Công nghệ phần mềm
(2, 3)



### Gom nhóm dữ liệu

##### 3 cách kết nối mới file ngoài máy tính
##### - Cách 1 (Kéo thả): Bấm vào icon Thư mục 📁 bên trái rồi kéo file từ máy tính thả trực tiếp vào giao diện Colab để dùng ngay lập tức.

##### - Cách 2 (Hộp thoại Upload): Chạy đoạn code from google.colab import files; files.upload() để hiện nút bấm chọn file trực quan từ máy thật.

##### - Cách 3 (Gắn Google Drive): Chạy code from google.colab import drive; drive.mount('/content/drive') để kết nối và đọc file lưu trữ vĩnh viễn trên Drive.

In [23]:
# Chuẩn bị dữ liệu mẫu phân cấp rõ ràng để gom nhóm
data = [
    ['Tên', 'Học viện', 'Cấp bậc', 'Điểm kiểm tra'],
    ['Gojo Satoru', 'Tokyo', 'Đặc cấp', 100],
    ['Yuta Okutsu', 'Tokyo', 'Đặc cấp', 95],
    ['Geto Suguru', 'Tokyo', 'Đặc cấp', 92],
    ['Itadori Yuji', 'Tokyo', 'Cấp 1', 85],
    ['Fushiguro Megumi', 'Tokyo', 'Cấp 1', 80],
    ['Kugisaki Nobara', 'Tokyo', 'Cấp 2', 75],
    ['Inumaki Toge', 'Tokyo', 'Cấp 2', 78],
    ['Todo Aoi', 'Kyoto', 'Cấp 1', 90],
    ['Mai Zenin', 'Kyoto', 'Cấp 3', 65],
    ['Miwa Kasumi', 'Kyoto', 'Cấp 3', 60],
    ['Kamo Noritoshi', 'Kyoto', 'Cấp 1', 82],
    ['Zenin Naobito', 'Kyoto', 'Cấp 1', 88]
]

with open(file='jujutsu_kaisen.csv', mode='w', newline='', encoding='utf-8') as file:
  writer = csv.writer(file)
  writer.writerows(data)

path = 'jujutsu_kaisen.csv'
df = pd.read_csv(path, skipinitialspace=True, names=None, sep=',', index_col=None)
print('Toàn bộ file:\n', df)
print(df.dtypes)
print(df.shape)
print('\n')

# Gom nhóm tính toán 1 cột
print('Gom nhóm theo học viện và cấp bậc (trung bình điểm kiểm tra):\n', df.groupby(['Học viện', 'Cấp bậc'])['Điểm kiểm tra'].mean())
print(df.dtypes)
print(df.shape)
print('\n')

# Thêm cột mới và ghi vào file csv
df['Tuổi'] = [28, 17, 28, 15, 15, 15, 17, 18, 16, 17, 18, 71]
path_afteradd='jujutsu_kaisen.csv'
df.to_csv(path_afteradd, index=False, encoding='utf-8') # index=False --> Phải có để Pandas không tự chèn thêm một cột số thứ tự vô danh
df_afteradd = pd.read_csv(filepath_or_buffer='jujutsu_kaisen.csv', skipinitialspace=True, names=None, sep=',')
print('Dữ liệu sau bổ sung:\n', df_afteradd)
print(df.dtypes)
print(df.shape)
print('\n')

# Gom nhóm  tính toán 2 cột
df_result = df.groupby(['Cấp bậc']).agg({
    'Điểm kiểm tra': ['min', 'max', 'mean'],
    'Tuổi': ['min', 'max', 'mean']
})
print('Gom nhóm theo cấp bậc:\n', df_result)
print(df_result.dtypes)
print(df_result.shape)
print('\n')

Toàn bộ file:
                  Tên Học viện  Cấp bậc  Điểm kiểm tra
0        Gojo Satoru    Tokyo  Đặc cấp            100
1        Yuta Okutsu    Tokyo  Đặc cấp             95
2        Geto Suguru    Tokyo  Đặc cấp             92
3       Itadori Yuji    Tokyo    Cấp 1             85
4   Fushiguro Megumi    Tokyo    Cấp 1             80
5    Kugisaki Nobara    Tokyo    Cấp 2             75
6       Inumaki Toge    Tokyo    Cấp 2             78
7           Todo Aoi    Kyoto    Cấp 1             90
8          Mai Zenin    Kyoto    Cấp 3             65
9        Miwa Kasumi    Kyoto    Cấp 3             60
10    Kamo Noritoshi    Kyoto    Cấp 1             82
11     Zenin Naobito    Kyoto    Cấp 1             88
Tên              object
Học viện         object
Cấp bậc          object
Điểm kiểm tra     int64
dtype: object
(12, 4)


Gom nhóm theo học viện và cấp bậc (trung bình điểm kiểm tra):
 Học viện  Cấp bậc
Kyoto     Cấp 1      86.666667
          Cấp 3      62.500000
Tokyo     Cấp 1     

# Thực hành TensorFlow

In [24]:
import tensorflow as tf
import numpy as np

## 1. Tensor 0 chiều

### Tensor 0-chiều gọi là scalar chỉ chứa 1 giá trị và không có trục.

In [25]:
# Kiểu mặc định là int32
rank_0_tensor = tf.constant(9)
print(rank_0_tensor)

r0_int8 = tf.constant(9, tf.int8)
print(r0_int8)

r0_float16 = tf.constant(9, tf.float16)
print(r0_float16)

r0_string = tf.constant('9', tf.string)
print(r0_string)

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int8)
tf.Tensor(9.0, shape=(), dtype=float16)
tf.Tensor(b'9', shape=(), dtype=string)


## 2. Tensor 1 chiều

### Tensor 1 chiều còn gọi là vector có 1 trục. Tensor 1-chiều giống như một danh sách

In [26]:
rank_1_tensor = tf.constant([1, 2, 3, 4], dtype = tf.float16)
print(rank_1_tensor)

tf.Tensor([1. 2. 3. 4.], shape=(4,), dtype=float16)


## 3. Tensor 2 chiều (ma trận)

### Là một ma trận hoặc có 2 trục

In [27]:
rank_2_tensor = tf.constant([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype = tf.int8)
print(rank_2_tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int8)


## 4. Tensor n chiều

In [28]:
rank_3_tensor = tf.constant([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
    ], dtype=tf.int8)
print(rank_3_tensor)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int8)


## 5. Thuộc tính của tensor

### Một tensor gồm có 3 thuộc tính:
### - Label (name)
### - Dimension (shape)
### - Data type (dtype)

In [29]:
rank_3_tensor = tf.constant([
    [
      [1, 2, 3, 4],
      [5, 6, 7, 8],
      [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
    ], dtype=tf.int8)
print(rank_3_tensor)
print('shape', rank_3_tensor.shape)
print('type o f tensor', rank_3_tensor.dtype)

tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]], shape=(2, 3, 4), dtype=int8)
shape (2, 3, 4)
type o f tensor <dtype: 'int8'>


## 6. Tạo tensor tự động gán giá trị ban đầu là 0

In [30]:
tensor_0 = tf.zeros(10)
print(tensor_0)
print(tensor_0.shape)
print(tensor_0.dtype, end="\n\n")

tensor_0_2d = tf.zeros([3, 5])
print(tensor_0_2d)
print(tensor_0_2d.shape)
print(tensor_0_2d.dtype, end="\n\n")

tensor_0_3d = tf.zeros([3, 5, 2])
print(tensor_0_3d)
print(tensor_0_3d.shape)
print(tensor_0_3d.dtype, end='\n\n')

tf.Tensor([0. 0. 0. 0. 0. 0. 0. 0. 0. 0.], shape=(10,), dtype=float32)
(10,)
<dtype: 'float32'>

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)
(3, 5)
<dtype: 'float32'>

tf.Tensor(
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]], shape=(3, 5, 2), dtype=float32)
(3, 5, 2)
<dtype: 'float32'>



## 7. Tạo tensor tạo tự động gán giá trị ban đầu là 1

In [31]:
t_1 = tf.ones(10)
print(t_1)
print(t_1.shape)
print(t_1.dtype, end='\n\n')

t_1_2d = tf.ones([3, 5])
print(t_1_2d)
print(t_1_2d.shape)
print(t_1_2d.dtype, end='\n\n')

t_1_3d = tf.ones([3, 5, 2], tf.int8)
print(t_1_3d)
print(t_1_3d.shape)
print(t_1_3d.dtype, end='\n\n')

tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1. 1. 1.], shape=(10,), dtype=float32)
(10,)
<dtype: 'float32'>

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(3, 5), dtype=float32)
(3, 5)
<dtype: 'float32'>

tf.Tensor(
[[[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]
  [1 1]
  [1 1]]], shape=(3, 5, 2), dtype=int8)
(3, 5, 2)
<dtype: 'int8'>



## 8. Tạo tensor tự động với giá trị bất kì

In [32]:
t_9 = tf.fill([3, 5], 9, tf.int8)
print(t_9)
print(t_9.shape)
print(t_9.dtype,end='\n\n')

tf.Tensor(
[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]], shape=(3, 5), dtype=int32)
(3, 5)
<dtype: 'int32'>



## 9. Tạo tensor 1 chiều với hàm linspace

In [33]:
lin_tensor = tf.linspace(5.0, 20.0, 5)
print(lin_tensor)
print(lin_tensor.shape)
print(lin_tensor.dtype)
# Code trên tạo 5 phần tử có giá trị trong khoảng [5.0, 20.0]

tf.Tensor([ 5.    8.75 12.5  16.25 20.  ], shape=(5,), dtype=float32)
(5,)
<dtype: 'float32'>


## 10. Tạo tensor 1 chiều với hàm range

### Hàm range tạo một tensor với số phần tử không được khai báo. Số phần tử sẽ được tính bằng cách công thêm giá trị delta

In [34]:
range = tf.range(3.0, 7.0, delta = 0.5)
print(range)
# Code trên tạo một tensor trong khoảng [3.0, 7.0), mỗi giá trị mới cộng thêm delta=0.5

range_tensor = tf.range(3, delta = 1)
print(range_tensor)
# Code trên tạo 1 tensor trong khoảng [0.0, 3.0) nếu ta không khai báo giá trị ban đầu thì mặc định sẽ bắt đầu là 0.0

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)
tf.Tensor([0 1 2], shape=(3,), dtype=int32)


## 11. Tạo tensor với giá trị ngẫu nhiên

###  Tạo tensor ngẫu nhiên với hàm random.normal

In [35]:
random_tensor = tf.random.normal([5])
print(range, end='\n\n')

random_tensor_2d = tf.random.normal([3, 5])
print(random_tensor_2d,end='\n\n')

random_tensor_3d = tf.random.normal([3, 5, 2])
print(random_tensor_3d, end='\n\n')

tf.Tensor([3.  3.5 4.  4.5 5.  5.5 6.  6.5], shape=(8,), dtype=float32)

tf.Tensor(
[[-1.4408588  -0.24626476  1.5776393   0.03040114  0.23193944]
 [-0.72628486  0.730779    2.5082133   0.3806997   0.56647885]
 [-0.5403088   0.03649897 -1.0972754   0.3613699  -0.9070746 ]], shape=(3, 5), dtype=float32)

tf.Tensor(
[[[-0.80782765 -0.27942562]
  [-1.0963722   1.2036374 ]
  [ 1.2915374  -0.68077374]
  [ 1.2499061   0.24703282]
  [-0.10783514 -0.32869223]]

 [[ 0.42279583  0.8679435 ]
  [-1.1011803  -0.6851386 ]
  [-0.94611275 -0.9343645 ]
  [ 0.14388661  0.7951058 ]
  [-0.23283944  0.61557114]]

 [[ 0.46669513 -0.33538404]
  [-0.84606344 -0.452306  ]
  [ 0.6680236   0.9847329 ]
  [ 2.1519816   1.5068669 ]
  [ 1.1055752  -1.2878215 ]]], shape=(3, 5, 2), dtype=float32)



###  Tạo tensor ngẫu nhiên với hàm random.uniform

In [36]:
range_tensor = tf.random.uniform([5], minval = 10, maxval = 20)
print(range_tensor, end='\n\n')

range_tensor_3d = tf.random.uniform([2, 5], minval = 10, maxval = 20)
print(range_tensor, end='\n\n')

range_tensor_3d = tf.random.uniform([2, 3, 2], minval = 10, maxval = 20)
print(range_tensor_3d, end='\n\n')

tf.Tensor([12.5431595 10.652094  17.031725  16.575207  16.093859 ], shape=(5,), dtype=float32)

tf.Tensor([12.5431595 10.652094  17.031725  16.575207  16.093859 ], shape=(5,), dtype=float32)

tf.Tensor(
[[[13.879902 11.939819]
  [10.50323  11.14787 ]
  [14.848603 19.143942]]

 [[14.327212 15.512151]
  [12.626048 12.481565]
  [11.608627 19.680264]]], shape=(2, 3, 2), dtype=float32)



### Tạo tensor ngẫu nhiên với hàm random.uniform và dùng shuffle để xáo trộn giá trị trong tensor

In [37]:
range_tensor = tf.random.uniform([5], minval = 5, maxval = 10)
print('No shuffle:\n', range_tensor)
print('Shuffle:\n', tf.random.shuffle(range_tensor))

No shuffle:
 tf.Tensor([5.017605 8.690023 8.283634 9.072201 7.593796], shape=(5,), dtype=float32)
Shuffle:
 tf.Tensor([8.690023 8.283634 7.593796 9.072201 5.017605], shape=(5,), dtype=float32)


### 12. Chuyển đổi kiểu dữ liệu

### Để chuyển từ kiểu dữ liệu này sang kiểu khác ta dùng hàm tf.cast

In [38]:
t_float = tf.constant(3.9, tf.float32)
print(t_float,'---',t_float.dtype)
t_float = tf.cast(t_float, tf.int8)
print(t_float,'---',t_float.dtype)

tf.Tensor(3.9, shape=(), dtype=float32) --- <dtype: 'float32'>
tf.Tensor(3, shape=(), dtype=int8) --- <dtype: 'int8'>


## 13. Các phép toán trong tensorflow

### 13.1.Tính căn bậc 2 của một tensor scalar

In [39]:
x = tf.constant(2, dtype=tf.float16)
print(tf.sqrt(x))

tf.Tensor(1.414, shape=(), dtype=float16)


### 13.2.Cộng 2 tensor

In [40]:
a = tf.constant([1, 2], dtype=tf.int8)
b = tf.constant([2, 4], dtype=tf.int8)
c = tf.add(a, b)
d = a + b
print(c)
print(d)

tf.Tensor([3 6], shape=(2,), dtype=int8)
tf.Tensor([3 6], shape=(2,), dtype=int8)


### 13.3. Nhân 2 tensor

In [41]:
a = tf.constant([1, 2], dtype=tf.int8)
b = tf.constant([2, 4], dtype=tf.int8)
c = tf.multiply(a, b)
d = (a * b)
print(c)
print(d)

tf.Tensor([2 8], shape=(2,), dtype=int8)
tf.Tensor([2 8], shape=(2,), dtype=int8)


### Các phép tính

In [42]:
a = tf.constant([9., 9., 9.], dtype=tf.float16)
b = tf.ones(3, tf.float16)*6
c = tf.ones(3, tf.float16)*3
d = tf.add(a, b)
e = tf.add_n([a, b, c])
f = tf.subtract(a, b)
g = tf.multiply(a, b)
h = tf.divide(a, b)
i = tf.scalar_mul(3, a)
j = tf.math.reciprocal(a)
k = tf.math.mod(a, b)
l = tf.negative(a)

print('a:\n', a)
print('b:\n', b)
print('c:\n', c)
print('add a, b:\n', d)
print('add_n a, b, c:\n', e)
print('substract a, b:\n', f)
print('multiply a, b:\n', g)
print('divide a, b:\n', h)
print('scalar_mul 3, a:\n', i)
print('reciprocal a:\n', j) # Tính giá trị nghịch đảo (1/a)
print('mod a, b:\n', k)
print('negative:\n', l)

a:
 tf.Tensor([9. 9. 9.], shape=(3,), dtype=float16)
b:
 tf.Tensor([6. 6. 6.], shape=(3,), dtype=float16)
c:
 tf.Tensor([3. 3. 3.], shape=(3,), dtype=float16)
add a, b:
 tf.Tensor([15. 15. 15.], shape=(3,), dtype=float16)
add_n a, b, c:
 tf.Tensor([18. 18. 18.], shape=(3,), dtype=float16)
substract a, b:
 tf.Tensor([3. 3. 3.], shape=(3,), dtype=float16)
multiply a, b:
 tf.Tensor([54. 54. 54.], shape=(3,), dtype=float16)
divide a, b:
 tf.Tensor([1.5 1.5 1.5], shape=(3,), dtype=float16)
scalar_mul 3, a:
 tf.Tensor([27. 27. 27.], shape=(3,), dtype=float16)
reciprocal a:
 tf.Tensor([0.1111 0.1111 0.1111], shape=(3,), dtype=float16)
mod a, b:
 tf.Tensor([3. 3. 3.], shape=(3,), dtype=float16)
negative:
 tf.Tensor([-9. -9. -9.], shape=(3,), dtype=float16)


## 14. Các phép toán làm tròn và so sánh

In [43]:
t = tf.constant([-6.5, -3.5, 3.5, 6.5])
r1 = tf.round(t)
r2 = tf.math.rint(t)
r3 = tf.math.ceil(t)
r4 = tf.math.floor(t)
print('t:\n', t)
print('round:\n', r1) # Nếu số nằm chính giữa (.5), làm tròn xa số 0 nhất
print('rint:\n', r2) # Nếu số nằm chính giữa (.5), làm tròn đến số nguyên chẵn gần nhất
print('ceil:\n',r3)
print('floor:\n', r4)

t:
 tf.Tensor([-6.5 -3.5  3.5  6.5], shape=(4,), dtype=float32)
round:
 tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
rint:
 tf.Tensor([-6. -4.  4.  6.], shape=(4,), dtype=float32)
ceil:
 tf.Tensor([-6. -3.  4.  7.], shape=(4,), dtype=float32)
floor:
 tf.Tensor([-7. -4.  3.  6.], shape=(4,), dtype=float32)


## 15. Các phép toán trên vector và ma trận

### - tf.tensordot(axes=0) (Tích ngoài): Nhân từng phần tử của vector này với vector kia để phóng to thành ma trận 2D.
### - tf.tensordot(axes=1) (Tích vô hướng): Nhân các cặp phần tử tương ứng rồi cộng tổng lại thành 1 con số duy nhất.
### - tf.linalg.cross() (Tích vector / Có hướng): Tạo ra một vector mới vuông góc với cả 2 vector ban đầu (chỉ dùng trong không gian 3D).
### - tf.matmul() (Nhân ma trận tiêu chuẩn): Nhân hàng của ma trận trước với cột của ma trận sau (số cột ma trận trước bắt buộc phải bằng số dòng ma trận sau).
### - tf.linalg.diag() (Tạo ma trận đường chéo): Bóc các dòng của ma trận cũ đem đặt làm đường chéo chính cho các ma trận vuông mới, xung quanh lấp đầy bằng số 0.
### - tf.linalg.trace() (Vết ma trận): Cộng tổng tất cả các phần tử nằm trên đường chéo chính của ma trận vuông.
### - tf.transpose() (Chuyển vị): Xoay ma trận bằng cách đổi toàn bộ dòng thành cột và cột thành dòng.
### - tf.eye() (Ma trận đơn vị): Tạo nhanh một ma trận vuông toàn số 0, riêng đường chéo chính toàn số 1.
### - tf.linalg (Thư viện Đại số tuyến tính): Không phải là một hàm, mà là "kho" chứa toàn bộ các phép toán nâng cao liên quan đến ma trận và vector như trên.

In [44]:
t1 = tf.constant([4., 3., 2.])
t2 = tf.constant([3., 2., 1.])
t3 = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
t4 = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
dot_x = tf.tensordot(t1, t2, 0) # Lấy từng phần tử t1 nhân từng phầ tử t2
dot_y = tf.tensordot(t1, t2, 1) # Nhân tương ứng phần tử t1 với t2 rồi cộng tất cả lại (tích vô hướng)
cross = tf.linalg.cross(t1, t2) # Tích vector
mm = tf.matmul(t3, t4)
d = tf.linalg.diag(t3)
trace = tf.linalg.trace(t3)
trans = tf.transpose(t3)
eye = tf.eye(5)

print('t1:\n', t1)
print('t2:\n', t2)
print('t3:\n', t3)
print('t4:\n', t4, end='\n\n')

print('Tensordot (axes = 0):\n', dot_x)
print('Tensordot (axes = 1):\n', dot_y)
print('Cross:\n', cross)
print('Matmul:\n', mm)
print('Diag:\n', d)
print('Trace:\n', trace)
print('Transpose:\n', trans)
print('Eye:\n', eye)

t1:
 tf.Tensor([4. 3. 2.], shape=(3,), dtype=float32)
t2:
 tf.Tensor([3. 2. 1.], shape=(3,), dtype=float32)
t3:
 tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
t4:
 tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32)

Tensordot (axes = 0):
 tf.Tensor(
[[12.  8.  4.]
 [ 9.  6.  3.]
 [ 6.  4.  2.]], shape=(3, 3), dtype=float32)
Tensordot (axes = 1):
 tf.Tensor(20.0, shape=(), dtype=float32)
Cross:
 tf.Tensor([-1.  2. -1.], shape=(3,), dtype=float32)
Matmul:
 tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)
Diag:
 tf.Tensor(
[[[1 0 0]
  [0 2 0]
  [0 0 3]]

 [[4 0 0]
  [0 5 0]
  [0 0 6]]], shape=(2, 3, 3), dtype=int32)
Trace:
 tf.Tensor(6, shape=(), dtype=int32)
Transpose:
 tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)
Eye:
 tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)


## 16. Biến trong tensorflow

### Khai báo biến trong tensor

In [45]:
toan = tf.Variable(8.5, dtype=tf.float16)
print('Toán: ', toan)
diem = tf.Variable([5, 9], dtype=tf.int8)
print('Điểm: ', diem)
print('Shape: ', diem.shape)
print('Dtype: ', diem.dtype)
print('Numpy: ', diem.numpy())

Toán:  <tf.Variable 'Variable:0' shape=() dtype=float16, numpy=8.5>
Điểm:  <tf.Variable 'Variable:0' shape=(2,) dtype=int8, numpy=array([5, 9], dtype=int8)>
Shape:  (2,)
Dtype:  <dtype: 'int8'>
Numpy:  [5 9]


### Gán giá trị cho tensor

In [46]:
toan = tf.Variable(8.5, dtype=tf.float16)
print('Toán: ', toan)
diem = tf.Variable([5, 9], dtype=tf.int8)
print('Điểm: ', diem)
diem.assign([8, 5])
print('Điểm sau khi gán: ', diem)
diem.assign_add([1, 2])
print('Điểm sau khi cộng: ', diem)
diem.assign_sub([9, 9])
print('Điểm sau khi trừ: ', diem)

Toán:  <tf.Variable 'Variable:0' shape=() dtype=float16, numpy=8.5>
Điểm:  <tf.Variable 'Variable:0' shape=(2,) dtype=int8, numpy=array([5, 9], dtype=int8)>
Điểm sau khi gán:  <tf.Variable 'Variable:0' shape=(2,) dtype=int8, numpy=array([8, 5], dtype=int8)>
Điểm sau khi cộng:  <tf.Variable 'Variable:0' shape=(2,) dtype=int8, numpy=array([9, 7], dtype=int8)>
Điểm sau khi trừ:  <tf.Variable 'Variable:0' shape=(2,) dtype=int8, numpy=array([ 0, -2], dtype=int8)>


## 17. Môi trường tính toán Graph trong tensorflow

### Graph có thể được sử dụng trong môi trường không cần bộ thông dịch Python như mobile, thiết bị nhúng,…
### Graph giúp tensorflow chạy nhanh, tính toán song song và trên nhiều thiết bị
### Graph là cấu trúc dữ liệu chứa các các đối tượng tf.Operation biểu diễn cho một đơn vị tính toán; và tf.Tensor biểu diễn cho một đơn vị dữ liệu truyền qua lại giữa các tf.Operation.

In [47]:
# Define a python function
def a_regular_function(x, y, b):
  x = tf.matmul(x, y)
  x += b
  return x

# 'a function that uses a graph' is a TensorFlow 'Function'
a_function_that_uses_a_graph = tf.function(a_regular_function)

# Make some tensors
x1 = tf.constant([[1., 2.]])
y1 = tf.constant([[2.], [3.]])
b1 = tf.constant(4.)

orig_value = a_regular_function(x1, y1, b1).numpy()

# Call a 'function' like a python function
tf_function_value = a_function_that_uses_a_graph(x1, y1, b1).numpy()

print(orig_value)
print(tf_function_value)

[[12.]]
[[12.]]


### 17.1.Biến một hàm Python thuần túy sang graph

#### Chỉ cần hàm cha là hàm Graph (@tf.function), thì tất cả các hàm con thông thường được gọi bên trong nó cũng sẽ tự động được biến thành hàm Graph.

In [48]:
def inner_function(x, y, b):
  x = tf.matmul(x, y)
  x += b
  return x

# Use the decorator to make 'outer_function' a 'Function'
@tf.function
def outer_function(x):
  y = tf.constant([[2.], [3.]])
  b = tf.constant(4.0)
  return inner_function(x, y, b)

# Note that the callable wiill create a graph that
# include 'inner_function' as well as 'outer_function'
rs = outer_function(tf.constant([[1., 2.]])).numpy()
print(rs)

[[12.]]


## 18. Modules, Layers và Models

###  Tạo lớp SimpleModule xử lý tensor scalar (Layer)

In [49]:
class SimpleModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)
    self.a_variable = tf.Variable(5.0, name="train_me")
    self.non_trainable_variable = tf.Variable(5.0, trainable=False,name="do_not_train_me")
  def __call__(self, x):
    return self.a_variable * x + self.non_trainable_variable

simple_module = SimpleModule(name="simple")

rs = simple_module(tf.constant(5.0))
print(rs)
print('Trainable variables', simple_module.trainable_variables)
print('All variables', simple_module.variables)

tf.Tensor(30.0, shape=(), dtype=float32)
Trainable variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>,)
All variables (<tf.Variable 'train_me:0' shape=() dtype=float32, numpy=5.0>, <tf.Variable 'do_not_train_me:0' shape=() dtype=float32, numpy=5.0>)


###  Tạo model với nhiều tầng (layer)

In [50]:
class Dense(tf.Module):
  def __init__(self, in_features, out_features, name=None):
    super().__init__(name=name)

    self.w = tf.Variable(
        tf.random.normal([in_features, out_features]), name='w')
    self.b = tf.Variable(tf.zeros([out_features]), name='b')

  def __call__(self, x):
    y = tf.matmul(x, self.w) + self.b
    return tf.nn.relu(y)

class SequentialModule(tf.Module):
  def __init__(self, name=None):
    super().__init__(name=name)

    self.dense_1 = Dense(in_features=3, out_features=3)
    self.dense_2 = Dense(in_features=3, out_features=2)

  def __call__(self, x):
    x = self.dense_1(x)
    return self.dense_2(x)

# You have a model!
my_model = SequentialModule(name="the_model")

# Call it, with random results
print('Model results: ', my_model(tf.constant([[2., 3., 4.]])))

Model results:  tf.Tensor([[0.       2.938877]], shape=(1, 2), dtype=float32)


#### Lớp Dense là một layer có hàm toán học Linear trong hàm __call__
#### Lớp SequentialModule là một model vì có chứa 2 layers Dense
#### Hàm relu có nhiệm vụ hạn chế việc model trả về kết quả tuyến tính và được định nghĩa
#### f(x) = max(0, x)

## 19. Lưu weight

### Chúng ta có thể lưu tf.Module ở dạng checkpoint lẫn SavedModel

### 19.1. Lưu checkpoint

#### Checkpoint là các weight (là giá trị của tập biến trong model hoặc submodel)

In [51]:
chkp_path = 'my_checkpoint'
checkpoint = tf.train.Checkpoint(model=my_model)
checkpoint.write(chkp_path)

'my_checkpoint'

#### Trong đoạn mã trên, tensorflow sẽ tạo 2 file
#### - my_checkpoint.data-00000-of-00001: chứa giá trị của các biến và đường dẫn chứa thuộc tính biến
#### - my_checkpoint.index: lưu trữ đánh số checkpoints.

### 19.2. Phục hồi checkpoint

#### Để nạp lại model đã lưu bằng checkpoint, ta dùng hàm restore

In [52]:
new_model = SequentialModule()
new_checkpoint = tf.train.Checkpoint(model=new_model)
new_checkpoint.restore('my_checkpoint')

# Should be the same result as above
print(new_model(tf.constant([[2., 3., 4.]])))

tf.Tensor([[0.       2.938877]], shape=(1, 2), dtype=float32)


# Bài tập

## Numpy

### 6. Viết chương trình tạo ma trận đơn vị 3 x 3 (đường chéo chính bằng 1, các phần tử còn lại 0)
### (Tìm hiểu hàm identity của numpy)

In [53]:
import numpy as np
a = np.identity(n=3, dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


### 12. Viết chương trình tạo mảng 3 x 3 x 3 và tính tổng theo mỗi dòng, mỗi cột. (tìm hiểu hàm sum của numpy)

#### builtins: là một "nhà kho" mặc định của Python, nơi lưu trữ tất cả các hàm cốt lõi nguyên bản nhất (như range(), print(), len(), int(),...).

In [54]:
import numpy as np
import builtins

In [55]:
a = np.random.randint(low=0, high=9, size=(3, 3, 3))
print(a)

for i in builtins.range(3):
  print('Ma trận:\n', a[i])
  print('Tổng theo mỗi dòng:', a[i].sum(axis=1))
  print('Tổng theo mỗi cột:', a[i].sum(axis=0), end='\n\n')

[[[8 1 1]
  [5 8 2]
  [8 5 8]]

 [[8 7 7]
  [6 5 5]
  [8 7 4]]

 [[6 8 5]
  [1 2 5]
  [1 1 3]]]
Ma trận:
 [[8 1 1]
 [5 8 2]
 [8 5 8]]
Tổng theo mỗi dòng: [10 15 21]
Tổng theo mỗi cột: [21 14 11]

Ma trận:
 [[8 7 7]
 [6 5 5]
 [8 7 4]]
Tổng theo mỗi dòng: [22 16 19]
Tổng theo mỗi cột: [22 19 16]

Ma trận:
 [[6 8 5]
 [1 2 5]
 [1 1 3]]
Tổng theo mỗi dòng: [19  8  5]
Tổng theo mỗi cột: [ 8 11 13]



# Pandas

### 15. Viết chương trình Pandas để cộng, trừ, nhân, chia 2 Series : [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [56]:
import pandas as pd

In [57]:
a = pd.Series([2, 4, 6, 8, 10])
b = pd.Series([1, 3, 5, 7, 10])
print('Tổng:\n', a.add(b, fill_value=1), end='\n\n')
print('Trừ:\n', a.sub(b, fill_value=1), end='\n\n')
print('Nhân:\n', a.mul(b, fill_value=1), end='\n\n')
print('Chia:\n', a.div(b, fill_value=1), end='\n\n')

Tổng:
 0     3
1     7
2    11
3    15
4    20
dtype: int64

Trừ:
 0    1
1    1
2    1
3    1
4    0
dtype: int64

Nhân:
 0      2
1     12
2     30
3     56
4    100
dtype: int64

Chia:
 0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.000000
dtype: float64



### 22. Viết chương trình Pandas tạo và hiển thị dữ liệu DataFrame sau
### exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
### 'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
### 'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
### 'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
### labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']


In [58]:
exam_data = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew',
'Laura', 'Kevin', 'Jonas'],
'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print(df)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes


### 29. Từ bài 22, cho biết những dòng có attempt > 2 và score trong khoảng (15, 20)

In [59]:
ket_qua = df[(df['attempts'] > 2) & (df['score'] >= 15) & (df['score'] <= 20)]
print(ket_qua)

      name  score  attempts qualify
f  Michael   20.0         3     yes


## TensorFlow

### 1. Tạo một tensor có kích thước [2, 3] với các phần tử được gán 0

In [60]:
import tensorflow as tf

In [61]:
ts_bai_1 = tf.zeros(shape=[2, 3], dtype=tf.int8)
print(ts_bai_1)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int8)


### 12. Viết hàm tạo 2 tensor ngẫu nhiên có kích thước x = (3, 2, 2), y = (3, 2, 2). Viết hàm tính cộng, trừ, nhân, chia sau đó chuyển các hàm này vào trong graph.


In [62]:
ts_bai_12_1 = tf.cast(tf.round(tf.random.normal(shape=[3, 2, 2])), dtype=tf.int8)
ts_bai_12_2 = tf.cast(tf.round(tf.random.normal(shape=[3, 2, 2])), dtype=tf.int8)

@tf.function
def ts_bai_12_cong():
  return tf.add(ts_bai_12_1, ts_bai_12_2)

@tf.function
def ts_bai_12_tru():
  return tf.subtract(ts_bai_12_1, ts_bai_12_2)

@tf.function
def ts_bai_12_nhan():
  return tf.multiply(ts_bai_12_1, ts_bai_12_2)

@tf.function
def ts_bai_12_chia():
  return tf.divide(ts_bai_12_1, ts_bai_12_2)

print('Tensor 1:\n', ts_bai_12_1, end='\n\n')
print('Tensor 2:\n', ts_bai_12_2, end='\n\n')

print('Tổng:\n', ts_bai_12_cong(), end='\n\n')
print('Trừ:\n', ts_bai_12_tru(), end='\n\n')
print('Nhân:\n', ts_bai_12_nhan(), end='\n\n')
print('Chia:\n', ts_bai_12_chia(), end='\n\n')

Tensor 1:
 tf.Tensor(
[[[ 0 -1]
  [ 1  0]]

 [[ 1  2]
  [-1  0]]

 [[ 0  2]
  [ 1  0]]], shape=(3, 2, 2), dtype=int8)

Tensor 2:
 tf.Tensor(
[[[ 0  2]
  [ 0  1]]

 [[ 1 -2]
  [-1 -1]]

 [[ 1 -1]
  [ 1 -1]]], shape=(3, 2, 2), dtype=int8)

Tổng:
 tf.Tensor(
[[[ 0  1]
  [ 1  1]]

 [[ 2  0]
  [-2 -1]]

 [[ 1  1]
  [ 2 -1]]], shape=(3, 2, 2), dtype=int8)

Trừ:
 tf.Tensor(
[[[ 0 -3]
  [ 1 -1]]

 [[ 0  4]
  [ 0  1]]

 [[-1  3]
  [ 0  1]]], shape=(3, 2, 2), dtype=int8)

Nhân:
 tf.Tensor(
[[[ 0 -2]
  [ 0  0]]

 [[ 1 -4]
  [ 1  0]]

 [[ 0 -2]
  [ 1  0]]], shape=(3, 2, 2), dtype=int8)

Chia:
 tf.Tensor(
[[[ nan -0.5]
  [ inf  0. ]]

 [[ 1.  -1. ]
  [ 1.  -0. ]]

 [[ 0.  -2. ]
  [ 1.  -0. ]]], shape=(3, 2, 2), dtype=float32)

