<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

In [ ]:
# Tạo mảng 1 chiều
import numpy as np

# Cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
# Chuyển list sang numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39, 5])
print('Numpy array tạo bằng cách 2: ', a)

# Kích thước mảng, kiểu dữ liệu
print('Kích thước mảng: ', a.shape)
print('Kiểu dữ liệu mảng: ', a.dtype)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
Numpy array tạo bằng cách 2:  [ 1  9 15 39  5]
Kích thước mảng:  (5,)
Kiểu dữ liệu mảng:  int64


In [ ]:
import numpy as np

# Mảng 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
import numpy as np

# Mảng 3 chiều
d = np.array([
    [[1., 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


In [ ]:
import numpy as np

# Tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros(3)
f = np.ones((2, 3, 4)) * 9
g = np.full((1, 2, 3, 4), 8)
print('Zeros matrix:\n', e)
print('Nines matrix:\n', f)
print('Eights matrix:\n', g)

Zeros matrix:
 [0. 0. 0.]
Nines matrix:
 [[[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]

 [[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]]
Eights matrix:
 [[[[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]

  [[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]]]
(1, 2, 3, 4)


### Để biết một ma trận có thể reshape sang những kích thước nào, bạn chỉ cần nhớ một quy tắc "vàng" duy nhất: Tổng số phần tử không được thay đổi.
### Tính tổng số phần tử (N) bằng cách nhân tất cả các con số trong shape lại với nhau.
### Ví dụ: $$N = 2 \times 2 \times 3 = 12 \text{ phần tử}$$

In [12]:
import numpy as np

# Reshape thay đổi kích thước ma trận
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận e: ', e.shape)
f = e.reshape(3, 2)
print(f)
print('Kích thước ma trận f: ', f.shape)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(g)
print('Kích thước ma trận g: ', g.shape)
print('Reshape (3, 4)')
h = g.reshape(3, 4)
print(h)
print('Kích thước ma trận h: ', h.shape)
print('Reshape (3, 2, 2)')
i = g.reshape(3, 2, -1) # Để -1 cho numpy tự tính
print(i)
print('Kích thước ma trận g: ', i.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận e:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Kích thước ma trận f:  (3, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kích thước ma trận g:  (2, 2, 3)
Reshape (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kích thước ma trận h:  (3, 4)
Reshape (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Kích thước ma trận g:  (3, 2, 2)


In [17]:
import numpy as np

# Plattern chuyển array nhiều chiều về 1 chiều
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận: ', e.shape)
f = e.flatten()
print(f)
print('Kích thước ma trận: ', f.shape)
g =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(g)
print('Kích thước ma trận: ', g.shape)
h = g.flatten()
print(f)
print('Kích thước ma trận: ', h.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)
[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)


In [20]:
# Thêm dòng dữ liệu với hstack và vstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
print('Horizontal append\n', h_stack)
v_stack = np.vstack((a, b))
print('Vertical append\n', v_stack)

Horizontal append
 [1 2 3 4 5 6]
Vertical append
 [[1 2 3]
 [4 5 6]]


In [23]:
# Sinh mảng số ngẫu nhiên
a = np.random.randint(size = (5,), low = 0, high = 10)
print(a)
b = np.random.randint(10, size = (5,))
print(b)


[8 2 9 2 6]
[2 5 0 5 6]
