<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

In [ ]:
# Tạo mảng 1 chiều
import numpy as np

# Cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
# Chuyển list sang numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39, 5])
print('Numpy array tạo bằng cách 2: ', a)

# Kích thước mảng, kiểu dữ liệu
print('Kích thước mảng: ', a.shape)
print('Kiểu dữ liệu mảng: ', a.dtype)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
Numpy array tạo bằng cách 2:  [ 1  9 15 39  5]
Kích thước mảng:  (5,)
Kiểu dữ liệu mảng:  int64


In [ ]:
import numpy as np

# Mảng 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [ ]:
import numpy as np

# Mảng 3 chiều
d = np.array([
    [[1., 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


In [ ]:
import numpy as np

# Tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros(3)
f = np.ones((2, 3, 4)) * 9
g = np.full((1, 2, 3, 4), 8)
print('Zeros matrix:\n', e)
print('Nines matrix:\n', f)
print('Eights matrix:\n', g)

Zeros matrix:
 [0. 0. 0.]
Nines matrix:
 [[[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]

 [[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]]
Eights matrix:
 [[[[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]

  [[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]]]
(1, 2, 3, 4)


### Để biết một ma trận có thể reshape sang những kích thước nào, bạn chỉ cần nhớ một quy tắc "vàng" duy nhất: Tổng số phần tử không được thay đổi.
### Tính tổng số phần tử (N) bằng cách nhân tất cả các con số trong shape lại với nhau.
### Ví dụ: $$N = 2 \times 2 \times 3 = 12 \text{ phần tử}$$

In [12]:
import numpy as np

# Reshape thay đổi kích thước ma trận
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận e: ', e.shape)
f = e.reshape(3, 2)
print(f)
print('Kích thước ma trận f: ', f.shape)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(g)
print('Kích thước ma trận g: ', g.shape)
print('Reshape (3, 4)')
h = g.reshape(3, 4)
print(h)
print('Kích thước ma trận h: ', h.shape)
print('Reshape (3, 2, 2)')
i = g.reshape(3, 2, -1) # Để -1 cho numpy tự tính
print(i)
print('Kích thước ma trận g: ', i.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận e:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Kích thước ma trận f:  (3, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kích thước ma trận g:  (2, 2, 3)
Reshape (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kích thước ma trận h:  (3, 4)
Reshape (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Kích thước ma trận g:  (3, 2, 2)


In [17]:
import numpy as np

# Plattern chuyển array nhiều chiều về 1 chiều
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận: ', e.shape)
f = e.flatten()
print(f)
print('Kích thước ma trận: ', f.shape)
g =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(g)
print('Kích thước ma trận: ', g.shape)
h = g.flatten()
print(f)
print('Kích thước ma trận: ', h.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)
[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)


In [20]:
# Thêm dòng dữ liệu với hstack và vstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
print('Horizontal append\n', h_stack)
v_stack = np.vstack((a, b))
print('Vertical append\n', v_stack)

Horizontal append
 [1 2 3 4 5 6]
Vertical append
 [[1 2 3]
 [4 5 6]]


In [26]:
# Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(size = (5,), low = 0, high = 10)
print('Sinh số ngẫu nhiên ma trận 1 chiều:\n', a)
b = np.random.randint(10, size = (5,))
print('Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):\n', b)
c = np.random.randint(size = (3, 6), low = 5, high = 30)
print('Sinh số ngẫu nhiên ma trận 3x6:\n', c)

Sinh số ngẫu nhiên ma trận 1 chiều:
 [1 1 5 9 1]
Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):
 [0 0 4 1 3]
Sinh số ngẫu nhiên ma trận 3x6:
 [[16 19 13 28 11 20]
 [ 8 26 29 28  7 10]
 [28  7 25 16 17 19]]


In [27]:
# Sinh mảng số thực ngẫu nhiên [0, 1)
a = np.random.rand(5)
print('Mảng 1 chiều:\n', a)
b = np.random.rand(3, 3, 2, 1)
print('Mảng 4 chiều:\n', b)

Mảng 1 chiều:
 [0.57310415 0.82843744 0.30390708 0.51542564 0.72450386]
Mảng 4 chiều:
 [[[[0.73780851]
   [0.15965324]]

  [[0.37053351]
   [0.85600068]]

  [[0.9607485 ]
   [0.13957315]]]


 [[[0.68426717]
   [0.13657644]]

  [[0.18793796]
   [0.76675728]]

  [[0.00268854]
   [0.74478464]]]


 [[[0.3323323 ]
   [0.54035962]]

  [[0.49620543]
   [0.88858828]]

  [[0.25592866]
   [0.33270545]]]]


### Ta dùng hàm
### Numpy.random.normal(loc, scale, size)
### Trong đó
### Loc: giá trị trung tâm
### Scale: độ lệch chuẩn
### Size: số phần tử trả về

#### Quy tắc dự đoán (3-Sigma):
#### 68% số sinh ra nằm trong: $[loc \pm scale]$
#### 95% số sinh ra nằm trong: $[loc \pm 2 \times scale]$ (Khoảng quan sát phổ biến nhất).
#### 99.7% số sinh ra nằm trong: $[loc \pm 3 \times scale]$ (Gần như toàn bộ).

#### Nếu bạn muốn sinh số ngẫu nhiên mà đa số nằm trong khoảng từ $A$ đến $B$:
#### 1. Chọn loc: Là điểm chính giữa của $A$ và $B$. ($loc = (A+B)/2$)
#### 2. Chọn scale: Lấy khoảng cách từ loc đến biên ($A$ hoặc $B$) rồi chia cho 2 hoặc 3.
####  - Chia 2: Nếu muốn 95% số nằm trong khoảng.
####  - Chia 3: Nếu muốn chắc chắn gần như 100% số nằm trong khoảng.
#### Ví dụ: Bạn muốn sinh số loanh quanh từ 10 đến 20:
####  - loc = 15
####  - scale = (20 - 15) / 2 = 2.5
####  - Lệnh: np.random.normal(15, 2.5, size=...)

In [28]:
# Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
a = np.random.normal(loc = 9, scale = 3, size = (4,))
print(a)

[ 7.16886326 12.4356087  13.16309031  8.91327829]


In [34]:
# Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 5, 6, 10, 9], size = (9,))
print(a)

# Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9], size = (3, 5))
print(b)

[10  2  5  6 10 10 10  6  9]
[[7 3 6 7 7]
 [7 1 5 8 4]
 [4 3 2 3 6]]


In [36]:
# Thay đổi giá trị của ma trận
A = np.matrix(np.ones((5, 6)))
print('The matrix\n', A)

The matrix
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
