<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

### 1. Tạo array 1 chiều


In [1]:
# Tạo mảng 1 chiều
import numpy as np

# Cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
# Chuyển list sang numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39, 5])
print('Numpy array tạo bằng cách 2: ', a)

# Kích thước mảng, kiểu dữ liệu
print('Kích thước mảng: ', a.shape)
print('Kiểu dữ liệu mảng: ', a.dtype)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
Numpy array tạo bằng cách 2:  [ 1  9 15 39  5]
Kích thước mảng:  (5,)
Kiểu dữ liệu mảng:  int64


### 2. Array 2 chiều

In [2]:
import numpy as np

# Mảng 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


### 3. Array 3 chiều

In [3]:
import numpy as np

# Mảng 3 chiều
d = np.array([
    [[1., 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


### 4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [4]:
import numpy as np

# Tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros(3)
f = np.ones((2, 3, 4)) * 9
g = np.full((1, 2, 3, 4), 8)
print('Zeros matrix:\n', e)
print('Nines matrix:\n', f)
print('Eights matrix:\n', g)

Zeros matrix:
 [0. 0. 0.]
Nines matrix:
 [[[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]

 [[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]]
Eights matrix:
 [[[[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]

  [[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]]]


### 5. Reshape và Flatten ma trận

#### 5.1. Reshape thay đổi kích thước ma trận

##### Để biết một ma trận có thể reshape sang những kích thước nào, bạn chỉ cần nhớ một quy tắc "vàng" duy nhất: Tổng số phần tử không được thay đổi.
##### Tính tổng số phần tử (N) bằng cách nhân tất cả các con số trong shape lại với nhau.
##### Ví dụ: $$N = 2 \times 2 \times 3 = 12 \text{ phần tử}$$

In [5]:
import numpy as np

# Reshape thay đổi kích thước ma trận
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận e: ', e.shape)
f = e.reshape(3, 2)
print(f)
print('Kích thước ma trận f: ', f.shape)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(g)
print('Kích thước ma trận g: ', g.shape)
print('Reshape (3, 4)')
h = g.reshape(3, 4)
print(h)
print('Kích thước ma trận h: ', h.shape)
print('Reshape (3, 2, 2)')
i = g.reshape(3, 2, -1) # Để -1 cho numpy tự tính
print(i)
print('Kích thước ma trận g: ', i.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận e:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Kích thước ma trận f:  (3, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kích thước ma trận g:  (2, 2, 3)
Reshape (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kích thước ma trận h:  (3, 4)
Reshape (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Kích thước ma trận g:  (3, 2, 2)


#### 5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [6]:
import numpy as np

# Plattern chuyển array nhiều chiều về 1 chiều
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận: ', e.shape)
f = e.flatten()
print(f)
print('Kích thước ma trận: ', f.shape)
g =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(g)
print('Kích thước ma trận: ', g.shape)
h = g.flatten()
print(f)
print('Kích thước ma trận: ', h.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)
[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)


### 6. Thêm dòng dữ liệu với hstack và vstack

In [7]:
# Thêm dòng dữ liệu với hstack và vstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
print('Horizontal append\n', h_stack)
v_stack = np.vstack((a, b))
print('Vertical append\n', v_stack)

Horizontal append
 [1 2 3 4 5 6]
Vertical append
 [[1 2 3]
 [4 5 6]]


### 7. Sinh mảng số ngẫu nhiên

#### 7.1. Sinh mảng số nguyên ngẫu nhiên

In [8]:
# Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(size = (5,), low = 0, high = 10)
print('Sinh số ngẫu nhiên ma trận 1 chiều:\n', a)
b = np.random.randint(10, size = (5,))
print('Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):\n', b)
c = np.random.randint(size = (3, 6), low = 5, high = 30)
print('Sinh số ngẫu nhiên ma trận 3x6:\n', c)

Sinh số ngẫu nhiên ma trận 1 chiều:
 [7 0 0 4 9]
Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):
 [2 2 5 3 0]
Sinh số ngẫu nhiên ma trận 3x6:
 [[12  6 29 29 27 16]
 [27 26 19 18  7 19]
 [20  5 15 17 17 17]]


#### 7.2. Sinh mảng số thực trong khoảng [0, 1]

In [9]:
# Sinh mảng số thực ngẫu nhiên [0, 1)
a = np.random.rand(5)
print('Mảng 1 chiều:\n', a)
b = np.random.rand(3, 3, 2, 1)
print('Mảng 4 chiều:\n', b)

Mảng 1 chiều:
 [0.89428094 0.52538637 0.6522461  0.84756544 0.92280665]
Mảng 4 chiều:
 [[[[0.9629924 ]
   [0.00477035]]

  [[0.76121253]
   [0.96261078]]

  [[0.50711116]
   [0.7272019 ]]]


 [[[0.1461886 ]
   [0.25484783]]

  [[0.99329395]
   [0.73876833]]

  [[0.4184546 ]
   [0.58349588]]]


 [[[0.07009277]
   [0.00985413]]

  [[0.60760504]
   [0.4249116 ]]

  [[0.98335581]
   [0.98194427]]]]


#### 7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

##### Ta dùng hàm
##### Numpy.random.normal(loc, scale, size)
##### Trong đó
##### Loc: giá trị trung tâm
##### Scale: độ lệch chuẩn
##### Size: số phần tử trả về

##### Quy tắc dự đoán (3-Sigma):
##### 68% số sinh ra nằm trong: $[loc \pm scale]$
##### 95% số sinh ra nằm trong: $[loc \pm 2 \times scale]$ (Khoảng quan sát phổ biến nhất).
##### 99.7% số sinh ra nằm trong: $[loc \pm 3 \times scale]$ (Gần như toàn bộ).

##### Nếu bạn muốn sinh số ngẫu nhiên mà đa số nằm trong khoảng từ $A$ đến $B$:
##### 1. Chọn loc: Là điểm chính giữa của $A$ và $B$. ($loc = (A+B)/2$)
##### 2. Chọn scale: Lấy khoảng cách từ loc đến biên ($A$ hoặc $B$) rồi chia cho 2 hoặc 3.
#####  - Chia 2: Nếu muốn 95% số nằm trong khoảng.
#####  - Chia 3: Nếu muốn chắc chắn gần như 100% số nằm trong khoảng.
##### Ví dụ: Bạn muốn sinh số loanh quanh từ 10 đến 20:
#####  - loc = 15
#####  - scale = (20 - 15) / 2 = 2.5
#####  - Lệnh: np.random.normal(15, 2.5, size=...)

In [10]:
# Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
a = np.random.normal(loc = 9, scale = 3, size = (4,))
print(a)

[ 8.0191169   9.46805223  4.75545492 10.21566416]


#### 7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [11]:
# Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 5, 6, 10, 9], size = (9,))
print(a)

# Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9], size = (3, 5))
print(b)

[10  5  9  5  5  5  5  6  6]
[[8 2 9 8 2]
 [6 4 9 6 3]
 [1 1 5 4 6]]


### 8. Thay đổi giá trị của ma trận

In [12]:
# Thay đổi giá trị của ma trận
A = np.matrix(np.ones((5, 6)))
print('The matrix\n', A)
np.array(A)[2] = 2 # array chỉ tạo bản sao của ma trận và tác động đến bản sao đó
print('The matrix with the change of row 3\n', A)
np.asarray(A)[2] = 2 # asarray tác động trực tiếp đến ma trận
print('The maxtrix with the change of row 3\n', A)

The matrix
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The matrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The maxtrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
