<a href="https://colab.research.google.com/github/tuhaovan917-ship-it/thuc_hanh_deeplearning/blob/main/buoi_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Thực hành numpy

### 1. Tạo array 1 chiều


In [1]:
# Tạo mảng 1 chiều
import numpy as np

# Cách 1
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
# Chuyển list sang numpy array
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

# Cách 2
a = np.array([1, 9, 15, 39, 5])
print('Numpy array tạo bằng cách 2: ', a)

# Kích thước mảng, kiểu dữ liệu
print('Kích thước mảng: ', a.shape)
print('Kiểu dữ liệu mảng: ', a.dtype)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]
Numpy array tạo bằng cách 2:  [ 1  9 15 39  5]
Kích thước mảng:  (5,)
Kiểu dữ liệu mảng:  int64


### 2. Array 2 chiều

In [2]:
import numpy as np

# Mảng 2 chiều
c = np.array([[1, 2, 3],
              [4, 5, 6]])
print(c)
print(c.shape)
print(c.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


### 3. Array 3 chiều

In [3]:
import numpy as np

# Mảng 3 chiều
d = np.array([
    [[1., 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(d)
print(d.shape)
print(d.dtype)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]]

 [[ 7.  8.  9.]
  [10. 11. 12.]]]
(2, 2, 3)
float64


### 4. Tạo Array với giá trị ban đầu là 0 hoặc 1

In [4]:
import numpy as np

# Tạo mảng với giá trị ban đầu là 0 hoặc 1
e = np.zeros(3)
f = np.ones((2, 3, 4)) * 9
g = np.full((1, 2, 3, 4), 8)
print('Zeros matrix:\n', e)
print('Nines matrix:\n', f)
print('Eights matrix:\n', g)

Zeros matrix:
 [0. 0. 0.]
Nines matrix:
 [[[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]

 [[9. 9. 9. 9.]
  [9. 9. 9. 9.]
  [9. 9. 9. 9.]]]
Eights matrix:
 [[[[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]

  [[8 8 8 8]
   [8 8 8 8]
   [8 8 8 8]]]]


### 5. Reshape và Flatten ma trận

#### 5.1. Reshape thay đổi kích thước ma trận

##### Để biết một ma trận có thể reshape sang những kích thước nào, bạn chỉ cần nhớ một quy tắc "vàng" duy nhất: Tổng số phần tử không được thay đổi.
##### Tính tổng số phần tử (N) bằng cách nhân tất cả các con số trong shape lại với nhau.
##### Ví dụ: $$N = 2 \times 2 \times 3 = 12 \text{ phần tử}$$

In [5]:
import numpy as np

# Reshape thay đổi kích thước ma trận
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận e: ', e.shape)
f = e.reshape(3, 2)
print(f)
print('Kích thước ma trận f: ', f.shape)
g = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])
print(g)
print('Kích thước ma trận g: ', g.shape)
print('Reshape (3, 4)')
h = g.reshape(3, 4)
print(h)
print('Kích thước ma trận h: ', h.shape)
print('Reshape (3, 2, 2)')
i = g.reshape(3, 2, -1) # Để -1 cho numpy tự tính
print(i)
print('Kích thước ma trận g: ', i.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận e:  (2, 3)
[[1 2]
 [3 4]
 [5 6]]
Kích thước ma trận f:  (3, 2)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Kích thước ma trận g:  (2, 2, 3)
Reshape (3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Kích thước ma trận h:  (3, 4)
Reshape (3, 2, 2)
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
Kích thước ma trận g:  (3, 2, 2)


#### 5.2. Platten là chuyển array nhiều chiều về 1 chiều

In [6]:
import numpy as np

# Plattern chuyển array nhiều chiều về 1 chiều
e = np.array([[1, 2, 3], [4, 5, 6]])
print(e)
print('Kích thước ma trận: ', e.shape)
f = e.flatten()
print(f)
print('Kích thước ma trận: ', f.shape)
g =  np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(g)
print('Kích thước ma trận: ', g.shape)
h = g.flatten()
print(f)
print('Kích thước ma trận: ', h.shape)

[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)
[[1 2 3]
 [4 5 6]]
Kích thước ma trận:  (2, 3)
[1 2 3 4 5 6]
Kích thước ma trận:  (6,)


### 6. Thêm dòng dữ liệu với hstack và vstack

In [7]:
# Thêm dòng dữ liệu với hstack và vstack

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
h_stack = np.hstack((a, b))
print('Horizontal append\n', h_stack)
v_stack = np.vstack((a, b))
print('Vertical append\n', v_stack)

Horizontal append
 [1 2 3 4 5 6]
Vertical append
 [[1 2 3]
 [4 5 6]]


### 7. Sinh mảng số ngẫu nhiên

#### 7.1. Sinh mảng số nguyên ngẫu nhiên

In [8]:
# Sinh mảng số nguyên ngẫu nhiên
a = np.random.randint(size = (5,), low = 0, high = 10)
print('Sinh số ngẫu nhiên ma trận 1 chiều:\n', a)
b = np.random.randint(10, size = (5,))
print('Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):\n', b)
c = np.random.randint(size = (3, 6), low = 5, high = 30)
print('Sinh số ngẫu nhiên ma trận 3x6:\n', c)

Sinh số ngẫu nhiên ma trận 1 chiều:
 [2 8 7 0 4]
Sinh số ngẫu nhiên ma trận 1 chiều (cách 2):
 [1 6 4 6 4]
Sinh số ngẫu nhiên ma trận 3x6:
 [[20 26 20 28 22 15]
 [25  7  8 11 28 13]
 [15  5  8 15 19 10]]


#### 7.2. Sinh mảng số thực trong khoảng [0, 1]

In [9]:
# Sinh mảng số thực ngẫu nhiên [0, 1)
a = np.random.rand(5)
print('Mảng 1 chiều:\n', a)
b = np.random.rand(3, 3, 2, 1)
print('Mảng 4 chiều:\n', b)

Mảng 1 chiều:
 [0.53009553 0.50255816 0.98510459 0.55274621 0.96658859]
Mảng 4 chiều:
 [[[[0.786822  ]
   [0.52919744]]

  [[0.36658576]
   [0.57607573]]

  [[0.66885025]
   [0.88896651]]]


 [[[0.71688465]
   [0.40374696]]

  [[0.62524832]
   [0.23309434]]

  [[0.91528569]
   [0.5420139 ]]]


 [[[0.5872416 ]
   [0.27056721]]

  [[0.82177756]
   [0.63203793]]

  [[0.07357365]
   [0.36660601]]]]


#### 7.3. Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian

##### Ta dùng hàm
##### Numpy.random.normal(loc, scale, size)
##### Trong đó
##### Loc: giá trị trung tâm
##### Scale: độ lệch chuẩn
##### Size: số phần tử trả về

##### Quy tắc dự đoán (3-Sigma):
##### 68% số sinh ra nằm trong: $[loc \pm scale]$
##### 95% số sinh ra nằm trong: $[loc \pm 2 \times scale]$ (Khoảng quan sát phổ biến nhất).
##### 99.7% số sinh ra nằm trong: $[loc \pm 3 \times scale]$ (Gần như toàn bộ).

##### Nếu bạn muốn sinh số ngẫu nhiên mà đa số nằm trong khoảng từ $A$ đến $B$:
##### 1. Chọn loc: Là điểm chính giữa của $A$ và $B$. ($loc = (A+B)/2$)
##### 2. Chọn scale: Lấy khoảng cách từ loc đến biên ($A$ hoặc $B$) rồi chia cho 2 hoặc 3.
#####  - Chia 2: Nếu muốn 95% số nằm trong khoảng.
#####  - Chia 3: Nếu muốn chắc chắn gần như 100% số nằm trong khoảng.
##### Ví dụ: Bạn muốn sinh số loanh quanh từ 10 đến 20:
#####  - loc = 15
#####  - scale = (20 - 15) / 2 = 2.5
#####  - Lệnh: np.random.normal(15, 2.5, size=...)

In [10]:
# Sinh mảng số ngẫu nhiên theo phân phối chuẩn Gaussian
a = np.random.normal(loc = 9, scale = 3, size = (4,))
print(a)

[ 9.82304199 13.48483252 10.11792754  9.32910978]


#### 7.4. Sinh ngẫu nhiên một giá trị từ mảng giá trị cho trước

In [11]:
# Sinh 1 giá trị ngẫu nhiên từ mảng giá trị cho trước
a = np.random.choice([2, 5, 6, 10, 9], size = (9,))
print(a)

# Sinh ma trận 3 x 5 ngẫu nhiên từ mảng giá trị cho trước
b = np.random.choice([1, 2, 3, 4, 5, 6, 7, 8, 9], size = (3, 5))
print(b)

[ 6  5 10  2  6  9  5  2  5]
[[7 9 7 9 2]
 [5 7 1 5 8]
 [1 9 4 9 6]]


### 8. Thay đổi giá trị của ma trận

In [12]:
# Thay đổi giá trị của ma trận
A = np.matrix(np.ones((5, 6)))
print('The matrix\n', A)
np.array(A)[2] = 2 # array chỉ tạo bản sao của ma trận và tác động đến bản sao đó
print('The matrix with the change of row 3\n', A)
np.asarray(A)[2] = 2 # asarray tác động trực tiếp đến ma trận
print('The maxtrix with the change of row 3\n', A)

The matrix
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The matrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
The maxtrix with the change of row 3
 [[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


### 9. Sinh dãy số theo khoảng cho trước

#### 9.1. Dùng hàm arrange

In [13]:
# Tạo 20 số nguyên từ 1 --> (n - 1)
a = np.arange(1, 20)
print(a)
# Tạo 20 số nguyên từ 1 --> (n - 1), mỗi bước tăng 2 giá trị
b = np.arange(1, 20, 2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


#### 9.2. Dùng hàm linspace

In [14]:
# Xếp num số cách đều nhau từ start đến end (tính luôn start và end) (num mặc định là 50)
a = np.linspace(1., 5., num=10)
print(a)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


### 10. Index và slice

##### Quy tắc lấy Index trong ma trận
##### - Giá trị trước dấu ‘,’ là số dòng
##### - Giá trị sau dấu ‘,’ là số cột
##### - Muốn chọn một dòng hoặc cột cụ thể thì cần thêm dấu ‘:’

In [15]:
# slice
a = np.array([(0, 1, 2), (3, 4, 5)])
print(a)
print('First row: ', a[0])
print('Second row: ', a[1])

# index
print('Second column: ', a[:, 1])
print('First row: ', a[0, :])
print('Fisrt row and 1 values: ', a[0, :4])

[[0 1 2]
 [3 4 5]]
First row:  [0 1 2]
Second row:  [3 4 5]
Second column:  [1 4]
First row:  [0 1 2]
Fisrt row and 1 values:  [0 1 2]


# Thực hành pandas

### Series là cấu trúc dữ liệu 1 chiều

In [16]:
import pandas as pd

# Tạo pandas series từ list
a = pd.Series([1., 2., 3.])
print(a)
print('First value: ', a[0])
b = pd.Series([1., 2., '3.'], index = ['a', 'b', 9])
print(b)
print('Second value: ', b['b'])
print('Third value: ', b[9])

# Tạo pandas series từ dictionary
calories = {"day 1": 420, "day 2": 380, 3: 390}
myvar = pd.Series(calories)
print(myvar)

0    1.0
1    2.0
2    3.0
dtype: float64
First value:  1.0
a    1.0
b    2.0
9     3.
dtype: object
Second value:  2.0
Third value:  3.
day 1    420
day 2    380
3        390
dtype: int64


### Chuyển đổi mạng dạng Numpy sang Pandas và ngược lại

In [17]:
# Numpy --> Pandas
h = np.array([[1, 2], [3, 4]])
df_h = pd.DataFrame(h)
print('DataFrame:\n', df_h)

# Pandas --> Numpy
numpy_h = np.array(df_h)
print('Numpy:\n', numpy_h)

DataFrame:
    0  1
0  1  2
1  3  4
Numpy:
 [[1 2]
 [3 4]]


### Tạo DataFrame 2 chiều có tên cột

In [18]:
dict = {'Tên': ['Văn', 'Thư'], 'Tuổi': [21, 21]}
df = pd.DataFrame(dict)
print(df)

   Tên  Tuổi
0  Văn    21
1  Thư    21


### In 5 dòng đầu tiên

In [19]:
a = np.random.randint(0, 9, size= (20, 4))
df = pd.DataFrame(a, columns = ['Cột 1', 'Cột 2', 'Cột 3', "Cột 4"])
print('In tất cả:\n', df)
print('In 5 dòng đầu tiên:\n', df.head())
print('In 15 dòng (trừ 5 dòng cuối):\n', df.head(-5))

In tất cả:
     Cột 1  Cột 2  Cột 3  Cột 4
0       4      4      1      8
1       5      7      0      7
2       0      6      1      3
3       4      1      4      3
4       0      7      6      5
5       1      2      5      0
6       4      4      4      5
7       1      8      8      3
8       2      6      4      1
9       6      2      6      0
10      1      0      6      5
11      6      3      2      1
12      0      6      1      6
13      3      6      1      5
14      6      8      0      6
15      3      6      4      8
16      4      6      3      3
17      8      2      8      2
18      5      3      7      4
19      6      7      0      5
In 5 dòng đầu tiên:
    Cột 1  Cột 2  Cột 3  Cột 4
0      4      4      1      8
1      5      7      0      7
2      0      6      1      3
3      4      1      4      3
4      0      7      6      5
In 15 dòng (trừ 5 dòng cuối):
     Cột 1  Cột 2  Cột 3  Cột 4
0       4      4      1      8
1       5      7      0      7
2       0   

### Chọn dòng, cột

In [20]:
a = np.random.rand(20, 5)
df = pd.DataFrame(a, columns = ['Số 1', 'Số 2', 'Số 3', 'Số 4', 'Số 5'])
print('Chọn 5 dòng cột 4:\n', df['Số 4'].head())

Chọn 5 dòng cột 4:
 0    0.401511
1    0.628927
2    0.185141
3    0.794142
4    0.153192
Name: Số 4, dtype: float64
